import type { ComprehensionQuestion } from './types'

export const comprehensionQuestions: ComprehensionQuestion[] = [
  // ── Difficulty 1 ──────────────────────────────────────────────
  {
    type: 'comprehension',
    id: 'co-013',
    difficulty: 1,
    passage: 'Anna har en liten katt. Katten liker å sove i sengen.',
    question: 'Hva liker katten til Anna å gjøre?',
    correct: 'Sove',
    choices: ['Sove', 'Løpe', 'Spise'],
  },
  {
    type: 'comprehension',
    id: 'co-014',
    difficulty: 1,
    passage: 'Jon har tre røde epler. Han gir ett til vennen sin.',
    question: 'Hvor mange epler har Jon igjen?',
    correct: 'To',
    choices: ['To', 'Tre', 'Fire'],
  },
  {
    type: 'comprehension',
    id: 'co-015',
    difficulty: 1,
    passage: 'Sola skinner og barna leker ute.',
    question: 'Hva gjør barna?',
    correct: 'Leker ute',
    choices: ['Leker ute', 'Sover', 'Spiser'],
  },
  {
    type: 'comprehension',
    id: 'co-001',
    difficulty: 1,
    passage: 'Petter har en hund som heter Voff. Voff er brun og glad.',
    question: 'Hva heter hunden til Petter?',
    correct: 'Voff',
    choices: ['Voff', 'Petter', 'Bjørn'],
  },
  {
    type: 'comprehension',
    id: 'co-002',
    difficulty: 1,
    passage: 'Lise har en rød bil. Hun kjører til butikken.',
    question: 'Hvilken farge er bilen til Lise?',
    correct: 'Rød',
    choices: ['Rød', 'Blå', 'Gul'],
  },

  // ── Difficulty 2 ──────────────────────────────────────────────
  {
    type: 'comprehension',
    id: 'co-016',
    difficulty: 2,
    passage: 'Emil har en blå sykkel. Han sykler til skolen hver dag.',
    question: 'Hvordan kommer Emil seg til skolen?',
    correct: 'På sykkel',
    choices: ['På sykkel', 'Med buss', 'Til fots'],
  },
  {
    type: 'comprehension',
    id: 'co-017',
    difficulty: 2,
    passage: 'Sara og bestemor baker boller på kjøkkenet. De bruker sukker og gjær.',
    question: 'Hva baker Sara og bestemor?',
    correct: 'Boller',
    choices: ['Boller', 'Brød', 'Kake'],
  },
  {
    type: 'comprehension',
    id: 'co-018',
    difficulty: 2,
    passage: 'En fugl bygger rede i et tre. Redet er laget av kvister.',
    question: 'Hva er redet laget av?',
    correct: 'Kvister',
    choices: ['Kvister', 'Blader', 'Stein'],
  },
  {
    type: 'comprehension',
    id: 'co-003',
    difficulty: 2,
    passage: 'Anders og Mia leker i skogen. De finner et fuglereir med tre egg. De passer på å ikke røre det.',
    question: 'Hva finner Anders og Mia i skogen?',
    correct: 'Et fuglereir med egg',
    choices: ['Et fuglereir med egg', 'En hund', 'En stor stein'],
  },
  {
    type: 'comprehension',
    id: 'co-004',
    difficulty: 2,
    passage: 'Mamma lager pannekaker til frokost. Hun bruker egg, mel og melk. Familien spiser dem med syltetøy.',
    question: 'Hva spiser familien pannekakene med?',
    correct: 'Syltetøy',
    choices: ['Syltetøy', 'Sukker', 'Honning'],
  },

  // ── Difficulty 3 ──────────────────────────────────────────────
  {
    type: 'comprehension',
    id: 'co-019',
    difficulty: 3,
    passage: 'En bjørn sover hele vinteren i en hule. Når våren kommer, våkner den og leter etter mat.',
    question: 'Når våkner bjørnen?',
    correct: 'Om våren',
    choices: ['Om våren', 'Om sommeren', 'Om høsten'],
  },
  {
    type: 'comprehension',
    id: 'co-020',
    difficulty: 3,
    passage: 'Mona har en venn som heter Ali. De liker å spille fotball sammen etter skolen.',
    question: 'Hva liker Mona og Ali å gjøre?',
    correct: 'Spille fotball',
    choices: ['Spille fotball', 'Lese bøker', 'Svømme'],
  },
  {
    type: 'comprehension',
    id: 'co-021',
    difficulty: 3,
    passage: 'En fisk lever i vann og puster med gjeller.',
    question: 'Hvordan puster fisken?',
    correct: 'Med gjeller',
    choices: ['Med gjeller', 'Med lunger', 'Med huden'],
  },
  {
    type: 'comprehension',
    id: 'co-005',
    difficulty: 3,
    passage: 'Elefanter er de største landdyrene på jorda. De lever i Afrika og Asia. Elefanter bruker snabelen sin til å drikke, spise og hilse på hverandre.',
    question: 'Hva bruker elefanter snabelen til?',
    correct: 'Drikke, spise og hilse',
    choices: ['Drikke, spise og hilse', 'Svømme og fly', 'Sove og hvile'],
  },

  // ── Difficulty 4 ──────────────────────────────────────────────
  {
    type: 'comprehension',
    id: 'co-022',
    difficulty: 4,
    passage: 'En gruppe barn planter blomster i skolegården. De vanner dem hver dag.',
    question: 'Hva gjør barna hver dag?',
    correct: 'Vanner blomstene',
    choices: ['Vanner blomstene', 'Plukker blomster', 'Leker'],
  },
  {
    type: 'comprehension',
    id: 'co-023',
    difficulty: 4,
    passage: 'En rev sniker seg gjennom skogen på jakt etter mat. Den er veldig stille.',
    question: 'Hva leter reven etter?',
    correct: 'Mat',
    choices: ['Mat', 'Vann', 'Blader'],
  },
  {
    type: 'comprehension',
    id: 'co-024',
    difficulty: 4,
    passage: 'En lærer skriver med kritt på tavla. Elevene følger nøye med.',
    question: 'Hva bruker læreren til å skrive på tavla?',
    correct: 'Kritt',
    choices: ['Kritt', 'Penn', 'Blyant'],
  },
  {
    type: 'comprehension',
    id: 'co-006',
    difficulty: 4,
    passage: 'Kari og Lars drar på fotballkamp. Laget deres spiller mot en skole fra nabobyen. I pausen er stillingen 1-0 til Karis lag. I andre omgang scorer Lars to mål, og laget vinner 3-0.',
    question: 'Hva var sluttresultatet?',
    correct: '3-0',
    choices: ['3-0', '1-0', '2-1'],
  },

  // ── Difficulty 5 ──────────────────────────────────────────────
  {
    type: 'comprehension',
    id: 'co-025',
    difficulty: 5,
    passage: 'En sommerfugl starter livet som et egg, blir til en larve, så en puppe, og til slutt en voksen sommerfugl.',
    question: 'Hva blir en larve til slutt?',
    correct: 'Sommerfugl',
    choices: ['Sommerfugl', 'Fugl', 'Bie'],
  },
  {
    type: 'comprehension',
    id: 'co-026',
    difficulty: 5,
    passage: 'En elv renner fra fjellet og ut i havet. Mange fisker lever i elva.',
    question: 'Hvor renner elva til slutt?',
    correct: 'Havet',
    choices: ['Havet', 'Fjellet', 'Skogen'],
  },
  {
    type: 'comprehension',
    id: 'co-027',
    difficulty: 5,
    passage: 'En baker lager brød og kaker hver dag. Han står opp tidlig om morgenen.',
    question: 'Hva lager bakeren?',
    correct: 'Brød og kaker',
    choices: ['Brød og kaker', 'Pizza', 'Suppe'],
  },
  {
    type: 'comprehension',
    id: 'co-007',
    difficulty: 5,
    passage: 'Pingviner er fugler, men de kan ikke fly. I stedet er de dyktige svømmere og tilbringer mye tid i havet. De lever i store kolonier og hjelper hverandre med å holde eggene varme i kulda på Antarktis.',
    question: 'Hvorfor kan ikke pingviner fly?',
    correct: 'Vingene er tilpasset til svømming',
    choices: ['Vingene er tilpasset til svømming', 'De er for tunge', 'De er redde for høyder'],
  },

  // ── Difficulty 6 ──────────────────────────────────────────────
  {
    type: 'comprehension',
    id: 'co-028',
    difficulty: 6,
    passage: 'En isbre er en stor masse av is som beveger seg sakte nedover fjellet. Isbreer kan forme landskapet over mange tusen år.',
    question: 'Hva kan isbreer gjøre med landskapet?',
    correct: 'Forme det',
    choices: ['Forme det', 'Smelte det', 'Farge det'],
  },
  {
    type: 'comprehension',
    id: 'co-029',
    difficulty: 6,
    passage: 'En geolog studerer steiner og jord for å forstå hvordan jorda er bygget opp.',
    question: 'Hva studerer en geolog?',
    correct: 'Steiner og jord',
    choices: ['Steiner og jord', 'Planter', 'Fugler'],
  },
  {
    type: 'comprehension',
    id: 'co-008',
    difficulty: 6,
    passage: 'Den norske fjellandsby Geilo er kjent for alpinanlegg og langrennsløyper. Om vinteren strømmer turister til fra hele Europa. Landsbyen har også sommertilbud som sykling og fjellvandring. Mange familier velger Geilo fordi det er aktiviteter for alle aldre.',
    question: 'Hva gjør Geilo populært for familier?',
    correct: 'Det er aktiviteter for alle aldre',
    choices: ['Det er aktiviteter for alle aldre', 'Det er billigst i Norge', 'Det har varmest vær'],
  },

  // ── Difficulty 7 ──────────────────────────────────────────────
  {
    type: 'comprehension',
    id: 'co-030',
    difficulty: 7,
    passage: 'En arkeolog graver ut gamle gjenstander for å lære om mennesker som levde for lenge siden.',
    question: 'Hva gjør en arkeolog?',
    correct: 'Graver ut gamle gjenstander',
    choices: ['Graver ut gamle gjenstander', 'Bygger hus', 'Lager mat'],
  },
  {
    type: 'comprehension',
    id: 'co-031',
    difficulty: 7,
    passage: 'En meteorolog bruker instrumenter for å forutsi været. De kan advare folk om stormer.',
    question: 'Hva kan en meteorolog advare om?',
    correct: 'Stormer',
    choices: ['Stormer', 'Jordskjelv', 'Flom'],
  },
  {
    type: 'comprehension',
    id: 'co-009',
    difficulty: 7,
    passage: 'Nordlyset, også kalt polarlyset, oppstår når ladede partikler fra sola kolliderer med gasser i Jordens atmosfære. Dette skaper vakre, fargede lys på himmelen. Det grønne lyset skyldes oksygen på lavere høyder, mens rødt lys oppstår høyere oppe. Nordlyset er best synlig nær polene, i land som Norge, Canada og Alaska.',
    question: 'Hva skaper det grønne lyset i nordlyset?',
    correct: 'Oksygen på lavere høyder',
    choices: ['Oksygen på lavere høyder', 'Nitrogen høyt oppe', 'Hydrogen ved overflaten'],
  },

  // ── Difficulty 8 ──────────────────────────────────────────────
  {
    type: 'comprehension',
    id: 'co-032',
    difficulty: 8,
    passage: 'En botaniker forsker på planter og hvordan de vokser i ulike miljøer.',
    question: 'Hva forsker en botaniker på?',
    correct: 'Planter',
    choices: ['Planter', 'Dyr', 'Fugler'],
  },
  {
    type: 'comprehension',
    id: 'co-033',
    difficulty: 8,
    passage: 'En vulkan kan sove i mange år før den plutselig får utbrudd og spyr ut lava og aske.',
    question: 'Hva kan en vulkan gjøre etter mange år?',
    correct: 'Få utbrudd',
    choices: ['Få utbrudd', 'Fryse', 'Forsvinne'],
  },
  {
    type: 'comprehension',
    id: 'co-010',
    difficulty: 8,
    passage: 'Klimaendringer påvirker isbreene i Arktis og Antarktis. Hvert år smelter store mengder is, noe som fører til at havnivået stiger. Dette truer kystnære byer rundt om i verden. Forskere advarer om at vi må redusere utslippene av klimagasser for å bremse denne utviklingen. Fornybar energi som sol og vind er viktige løsninger.',
    question: 'Hva er en konsekvens av at isbreene smelter?',
    correct: 'Havnivået stiger',
    choices: ['Havnivået stiger', 'Temperaturen synker', 'Det blir mer nedbør'],
  },

  // ── Difficulty 9 ──────────────────────────────────────────────
  {
    type: 'comprehension',
    id: 'co-034',
    difficulty: 9,
    passage: 'En astrofysiker studerer stjerner og galakser for å forstå universets opprinnelse.',
    question: 'Hva studerer en astrofysiker?',
    correct: 'Stjerner og galakser',
    choices: ['Stjerner og galakser', 'Fjell og elver', 'Planter og dyr'],
  },
  {
    type: 'comprehension',
    id: 'co-035',
    difficulty: 9,
    passage: 'En epidemiolog undersøker hvordan sykdommer sprer seg i befolkningen og hvordan de kan stoppes.',
    question: 'Hva undersøker en epidemiolog?',
    correct: 'Sykdommer',
    choices: ['Sykdommer', 'Vær', 'Maskiner'],
  },
  {
    type: 'comprehension',
    id: 'co-011',
    difficulty: 9,
    passage: 'Menneskekroppen har over 600 muskler som jobber sammen for å skape bevegelse. Hjertet er den hardest arbeidende muskelen, og slår over 100 000 ganger i døgnet. Mellomgulvet er en viktig muskel under lungene som kontrollerer innåndingen. Uten musklene ville vi ikke kunne gå, prate eller til og med puste.',
    question: 'Hva er mellomgulvets funksjon?',
    correct: 'Kontrollere innåndingen',
    choices: ['Kontrollere innåndingen', 'Pumpe blod', 'Fordøye mat'],
  },

  // ── Difficulty 10 ─────────────────────────────────────────────
  {
    type: 'comprehension',
    id: 'co-036',
    difficulty: 10,
    passage: 'En nevrolog forsker på hjernen og nervesystemet for å forstå hvordan tanker og følelser oppstår.',
    question: 'Hva forsker en nevrolog på?',
    correct: 'Hjernen og nervesystemet',
    choices: ['Hjernen og nervesystemet', 'Hjertet', 'Lungene'],
  },
  {
    type: 'comprehension',
    id: 'co-037',
    difficulty: 10,
    passage: 'En klimaforsker bruker datamodeller for å forutsi hvordan klimaet vil endre seg i fremtiden.',
    question: 'Hva bruker en klimaforsker for å forutsi klimaendringer?',
    correct: 'Datamodeller',
    choices: ['Datamodeller', 'Kikkert', 'Termometer'],
  },
  {
    type: 'comprehension',
    id: 'co-012',
    difficulty: 10,
    passage: 'Kvantedatamaskiner utnytter prinsippene fra kvantefysikk for å utføre beregninger som tradisjonelle datamaskiner ikke kan. I stedet for bits som er enten 0 eller 1, bruker de kvantebits (qubits) som kan eksistere i begge tilstander samtidig – et fenomen kalt superposisjon. I tillegg kan qubits "sammenfiltres", noe som betyr at tilstanden til én qubit øyeblikkelig påvirker en annen, uansett avstand. Dette åpner for revolusjonerende fremskritt innen kryptografi, medisin og kunstig intelligens.',
    question: 'Hva kalles fenomenet der en qubit kan være i to tilstander samtidig?',
    correct: 'Superposisjon',
    choices: ['Superposisjon', 'Sammenfiltring', 'Kvantebit', 'Dekoherens'],
  },
]
