import type { PunctuationQuestion } from './types'

export const punctuationQuestions: PunctuationQuestion[] = [
  // ── Difficulty 1 ──────────────────────────────────────────────
  {
    type: 'punctuation',
    id: 'pu-045',
    difficulty: 1,
    sentence: 'Du er best',
    correct: '!',
    choices: ['.', '?', '!'],
    teachingNote: 'Utrop og sterke følelser slutter med utropstegn.'
  },
  {
    type: 'punctuation',
    id: 'pu-046',
    difficulty: 1,
    sentence: 'Hopp nå',
    correct: '!',
    choices: ['.', '?', '!'],
    teachingNote: 'Korte kommandoer og oppfordringer slutter ofte med utropstegn.'
  },
  {
    type: 'punctuation',
    id: 'pu-001',
    difficulty: 1,
    sentence: 'Hunden er stor',
    correct: '.',
    choices: ['.', '?', '!'],
    teachingNote: 'Påstandssetninger slutter med punktum.',
  },
  {
    type: 'punctuation',
    id: 'pu-002',
    difficulty: 1,
    sentence: 'Heter du Per',
    correct: '?',
    choices: ['.', '?', '!'],
    teachingNote: 'Spørsmål slutter med spørsmålstegn.',
  },
  {
    type: 'punctuation',
    id: 'pu-003',
    difficulty: 1,
    sentence: 'Se på den store bilen',
    correct: '!',
    choices: ['.', '?', '!'],
    teachingNote: 'Utrop og sterke følelser slutter med utropstegn.',
  },
  {
    type: 'punctuation',
    id: 'pu-004',
    difficulty: 1,
    sentence: 'Katten er hvit',
    correct: '.',
    choices: ['.', '?', '!'],
    teachingNote: 'Påstandssetninger slutter med punktum.',
  },
  {
    type: 'punctuation',
    id: 'pu-005',
    difficulty: 1,
    sentence: 'Hva er det der',
    correct: '?',
    choices: ['.', '?', '!'],
    teachingNote: 'Spørsmål slutter med spørsmålstegn.',
  },

  // ── Difficulty 2 ──────────────────────────────────────────────
  {
    type: 'punctuation',
    id: 'pu-047',
    difficulty: 2,
    sentence: 'Hjelp meg',
    correct: '!',
    choices: ['.', '?', '!'],
    teachingNote: 'Sterke oppfordringer og rop slutter med utropstegn.'
  },
  {
    type: 'punctuation',
    id: 'pu-048',
    difficulty: 2,
    sentence: 'Flytt deg',
    correct: '!',
    choices: ['.', '?', '!'],
    teachingNote: 'Kommandoer og advarsler slutter ofte med utropstegn.'
  },
  {
    type: 'punctuation',
    id: 'pu-049',
    difficulty: 2,
    sentence: 'Pass opp',
    correct: '!',
    choices: ['.', '?', '!'],
    teachingNote: 'Advarsler og utrop slutter med utropstegn.'
  },
  {
    type: 'punctuation',
    id: 'pu-006',
    difficulty: 2,
    sentence: 'Bilen er rød og stor',
    correct: '.',
    choices: ['.', '?', '!'],
    teachingNote: 'En oppramsing i en påstand avsluttes med punktum.',
  },
  {
    type: 'punctuation',
    id: 'pu-007',
    difficulty: 2,
    sentence: 'Kan du hjelpe meg',
    correct: '?',
    choices: ['.', '?', '!'],
    teachingNote: 'Høflige spørsmål slutter med spørsmålstegn.',
  },
  {
    type: 'punctuation',
    id: 'pu-008',
    difficulty: 2,
    sentence: 'Hurra, vi har vunnet',
    correct: '!',
    choices: ['.', '?', '!'],
    teachingNote: 'Gledesutrop slutter med utropstegn.',
  },
  {
    type: 'punctuation',
    id: 'pu-009',
    difficulty: 2,
    sentence: 'Fuglen sitter i treet',
    correct: '.',
    choices: ['.', '?', '!'],
    teachingNote: 'Enkle påstandssetninger slutter med punktum.',
  },
  {
    type: 'punctuation',
    id: 'pu-010',
    difficulty: 2,
    sentence: 'Hvor bor du',
    correct: '?',
    choices: ['.', '?', '!'],
    teachingNote: 'Spørsmål som begynner med et spørreord slutter med spørsmålstegn.',
  },

  // ── Difficulty 3 ──────────────────────────────────────────────
  {
    type: 'punctuation',
    id: 'pu-011',
    difficulty: 3,
    sentence: 'Vi spiser frokost hver morgen',
    correct: '.',
    choices: ['.', '?', '!'],
    teachingNote: 'Dagligdagse påstander avsluttes med punktum.',
  },
  {
    type: 'punctuation',
    id: 'pu-012',
    difficulty: 3,
    sentence: 'Hva heter søsteren din',
    correct: '?',
    choices: ['.', '?', '!'],
    teachingNote: 'Spørsmål om noen begynner med spørreord og slutter med spørsmålstegn.',
  },
  {
    type: 'punctuation',
    id: 'pu-013',
    difficulty: 3,
    sentence: 'Pass deg for hunden',
    correct: '!',
    choices: ['.', '?', '!'],
    teachingNote: 'Advarsler og oppfordringer kan slutte med utropstegn.',
  },
  {
    type: 'punctuation',
    id: 'pu-014',
    difficulty: 3,
    sentence: 'Elefanten er det største landdyret',
    correct: '.',
    choices: ['.', '?', '!'],
    teachingNote: 'En faktapåstand avsluttes med punktum.',
  },
  {
    type: 'punctuation',
    id: 'pu-015',
    difficulty: 3,
    sentence: 'Har du sett den nye filmen',
    correct: '?',
    choices: ['.', '?', '!'],
    teachingNote: 'Ja/nei-spørsmål slutter med spørsmålstegn.',
  },

  // ── Difficulty 4 ──────────────────────────────────────────────
  {
    type: 'punctuation',
    id: 'pu-050',
    difficulty: 4,
    sentence: 'Han leker med LEGO',
    correct: '.',
    choices: ['.', '?', '!'],
    teachingNote: 'En enkel påstand avsluttes med punktum.'
  },
  {
    type: 'punctuation',
    id: 'pu-016',
    difficulty: 4,
    sentence: 'Brannbilen kom raskt til stedet',
    correct: '.',
    choices: ['.', '?', '!'],
    teachingNote: 'Påstandssetninger med tidsadverb avsluttes med punktum.',
  },
  {
    type: 'punctuation',
    id: 'pu-017',
    difficulty: 4,
    sentence: 'Hvilken vei skal vi gå',
    correct: '?',
    choices: ['.', '?', '!'],
    teachingNote: 'Spørsmål om valg slutter med spørsmålstegn.',
  },
  {
    type: 'punctuation',
    id: 'pu-018',
    difficulty: 4,
    sentence: 'Stopp, du får ikke lov til det',
    correct: '!',
    choices: ['.', '?', '!'],
    teachingNote: 'Kommandoer og forbud slutter ofte med utropstegn.',
  },
  {
    type: 'punctuation',
    id: 'pu-019',
    difficulty: 4,
    sentence: 'Pingviner lever i Antarktis',
    correct: '.',
    choices: ['.', '?', '!'],
    teachingNote: 'Geografiske fakta avsluttes med punktum.',
  },
  {
    type: 'punctuation',
    id: 'pu-020',
    difficulty: 4,
    sentence: 'Liker du å spille fotball',
    correct: '?',
    choices: ['.', '?', '!'],
    teachingNote: 'Spørsmål om preferanser slutter med spørsmålstegn.',
  },

  // ── Difficulty 5 ──────────────────────────────────────────────
  {
    type: 'punctuation',
    id: 'pu-021',
    difficulty: 5,
    sentence: 'Helikopteret landet trygt på taket',
    correct: '.',
    choices: ['.', '?', '!'],
    teachingNote: 'Påstandssetninger med stedsadverb avsluttes med punktum.',
  },
  {
    type: 'punctuation',
    id: 'pu-022',
    difficulty: 5,
    sentence: 'Hvorfor smelter isbreene så raskt',
    correct: '?',
    choices: ['.', '?', '!'],
    teachingNote: 'Hvorfor-spørsmål slutter med spørsmålstegn.',
  },
  {
    type: 'punctuation',
    id: 'pu-023',
    difficulty: 5,
    sentence: 'Så utrolig fint nordlyset er',
    correct: '!',
    choices: ['.', '?', '!'],
    teachingNote: 'Beundringsutsagn som begynner med "Så" slutter med utropstegn.',
  },
  {
    type: 'punctuation',
    id: 'pu-024',
    difficulty: 5,
    sentence: 'Klatring i fjell krever mye styrke',
    correct: '.',
    choices: ['.', '?', '!'],
    teachingNote: 'Allmenne påstander avsluttes med punktum.',
  },
  {
    type: 'punctuation',
    id: 'pu-025',
    difficulty: 5,
    sentence: 'Hvor mange øvelser er det i friidrett',
    correct: '?',
    choices: ['.', '?', '!'],
    teachingNote: 'Mengdespørsmål slutter med spørsmålstegn.',
  },

  // ── Difficulty 6 ──────────────────────────────────────────────
  {
    type: 'punctuation',
    id: 'pu-051',
    difficulty: 6,
    sentence: 'Engelsk er et språk',
    correct: '.',
    choices: ['.', '?', '!'],
    teachingNote: 'Faktasetninger avsluttes med punktum.'
  },
  {
    type: 'punctuation',
    id: 'pu-026',
    difficulty: 6,
    sentence: 'Vulkanen spydde lava ned fjellsiden',
    correct: '.',
    choices: ['.', '?', '!'],
    teachingNote: 'Naturvitenskapelige beskrivelser avsluttes med punktum.',
  },
  {
    type: 'punctuation',
    id: 'pu-027',
    difficulty: 6,
    sentence: 'Har du noen gang sett en flodhest på nært hold',
    correct: '?',
    choices: ['.', '?', '!'],
    teachingNote: 'Erfaringsspørsmål slutter med spørsmålstegn.',
  },
  {
    type: 'punctuation',
    id: 'pu-028',
    difficulty: 6,
    sentence: 'Hvilken utrolig prestasjon av løperne',
    correct: '!',
    choices: ['.', '?', '!'],
    teachingNote: 'Beundringsutrop om en prestasjon slutter med utropstegn.',
  },
  {
    type: 'punctuation',
    id: 'pu-029',
    difficulty: 6,
    sentence: 'Ubåten dykket ned til havbunnen',
    correct: '.',
    choices: ['.', '?', '!'],
    teachingNote: 'Fortellesetninger slutter med punktum.',
  },
  {
    type: 'punctuation',
    id: 'pu-030',
    difficulty: 6,
    sentence: 'Når ble Norge selvstendig',
    correct: '?',
    choices: ['.', '?', '!'],
    teachingNote: 'Historiske spørsmål slutter med spørsmålstegn.',
  },

  // ── Difficulty 7 ──────────────────────────────────────────────
  {
    type: 'punctuation',
    id: 'pu-031',
    difficulty: 7,
    sentence: 'Nordlyset oppstår fordi ladede partikler treffer atmosfæren',
    correct: '.',
    choices: ['.', '?', '!'],
    teachingNote: 'Årsaksforklaringer i en påstand avsluttes med punktum.',
  },
  {
    type: 'punctuation',
    id: 'pu-032',
    difficulty: 7,
    sentence: 'Hvor mange qubits trenger en kvantemaskin for å slå en klassisk datamaskin',
    correct: '?',
    choices: ['.', '?', '!'],
    teachingNote: 'Tekniske mengdespørsmål slutter med spørsmålstegn.',
  },
  {
    type: 'punctuation',
    id: 'pu-033',
    difficulty: 7,
    sentence: 'For en fantastisk oppdagelse av forskerne',
    correct: '!',
    choices: ['.', '?', '!'],
    teachingNote: 'Opphissede utrop om oppdagelser slutter med utropstegn.',
  },
  {
    type: 'punctuation',
    id: 'pu-034',
    difficulty: 7,
    sentence: 'Sjimpansen løste problemet raskere enn forventet',
    correct: '.',
    choices: ['.', '?', '!'],
    teachingNote: 'Setninger med sammenligningsledd er påstander og avsluttes med punktum.',
  },

  // ── Difficulty 8 ──────────────────────────────────────────────
  {
    type: 'punctuation',
    id: 'pu-052',
    difficulty: 8,
    sentence: 'Og så ropte jeg: LØP',
    correct: '!',
    choices: ['.', '?', '!'],
    teachingNote: 'Replikk og utrop slutter med utropstegn.'
  },
  {
    type: 'punctuation',
    id: 'pu-035',
    difficulty: 8,
    sentence: 'Mellomgulvet er en viktig muskel som kontrollerer pusten',
    correct: '.',
    choices: ['.', '?', '!'],
    teachingNote: 'Definisjonssetninger er påstander og avsluttes med punktum.',
  },
  {
    type: 'punctuation',
    id: 'pu-036',
    difficulty: 8,
    sentence: 'Kan fornybar energi erstatte all bruk av fossile brensler',
    correct: '?',
    choices: ['.', '?', '!'],
    teachingNote: 'Åpne ja/nei-spørsmål om fremtiden slutter med spørsmålstegn.',
  },
  {
    type: 'punctuation',
    id: 'pu-037',
    difficulty: 8,
    sentence: 'Det er utrolig at en fugl uten evne til å fly klarer å overleve',
    correct: '!',
    choices: ['.', '?', '!'],
    teachingNote: 'Setninger som uttrykker sterk overraskelse kan slutte med utropstegn.',
  },
  {
    type: 'punctuation',
    id: 'pu-038',
    difficulty: 8,
    sentence: 'Jordskjelv måles på Richterskalaen',
    correct: '.',
    choices: ['.', '?', '!'],
    teachingNote: 'Faglige faktasetninger avsluttes med punktum.',
  },

  // ── Difficulty 9 ──────────────────────────────────────────────
  {
    type: 'punctuation',
    id: 'pu-053',
    difficulty: 9,
    sentence: 'Dette er det kuleste jeg noen sinne har sett',
    correct: '!',
    choices: ['.', '?', '!'],
    teachingNote: 'Sterke beundringsutrop slutter med utropstegn.'
  },
  {
    type: 'punctuation',
    id: 'pu-039',
    difficulty: 9,
    sentence: 'Superposisjon betyr at en qubit kan eksistere i to tilstander på samme tid',
    correct: '.',
    choices: ['.', '?', '!'],
    teachingNote: 'Vitenskapelige definisjoner er påstandssetninger og avsluttes med punktum.',
  },
  {
    type: 'punctuation',
    id: 'pu-040',
    difficulty: 9,
    sentence: 'Hvordan kan kvantefysikk brukes til å forbedre kryptografi',
    correct: '?',
    choices: ['.', '?', '!'],
    teachingNote: 'Åpne fagspørsmål slutter med spørsmålstegn.',
  },
  {
    type: 'punctuation',
    id: 'pu-041',
    difficulty: 9,
    sentence: 'Monsunregnet er avgjørende for landbruket i store deler av Asia',
    correct: '.',
    choices: ['.', '?', '!'],
    teachingNote: 'Geografiske og klimatiske fakta avsluttes med punktum.',
  },

  // ── Difficulty 10 ─────────────────────────────────────────────
  {
    type: 'punctuation',
    id: 'pu-042',
    difficulty: 10,
    sentence: 'Kvantesammenfiltring innebærer at to qubits er korrelert uansett avstand',
    correct: '.',
    choices: ['.', '?', '!'],
    teachingNote: 'Komplekse vitenskapelige påstander avsluttes med punktum.',
  },
  {
    type: 'punctuation',
    id: 'pu-043',
    difficulty: 10,
    sentence: 'Vil kvanteberegning revolusjonere medisinsk forskning innen 2040',
    correct: '?',
    choices: ['.', '?', '!'],
    teachingNote: 'Fremtidsspørsmål med tidsangivelse slutter med spørsmålstegn.',
  },
  {
    type: 'punctuation',
    id: 'pu-044',
    difficulty: 10,
    sentence: 'Hjerteklaffen pumper blod gjennom hele kroppen uten å stoppe',
    correct: '.',
    choices: ['.', '?', '!'],
    teachingNote: 'Biologiske fakta om kroppens funksjoner avsluttes med punktum.',
  },
]
