import type { RhymeQuestion } from './types'

export const rhymeQuestions: RhymeQuestion[] = [
  // D1 — 3 choices
  { type: 'rhyme', id: 'rhy-001', difficulty: 1, word: 'katt',  correct: 'hatt',  choices: ['hatt',  'bil',   'sko'] },
  { type: 'rhyme', id: 'rhy-002', difficulty: 1, word: 'hus',   correct: 'mus',   choices: ['mus',   'fugl',  'sol'] },
  { type: 'rhyme', id: 'rhy-003', difficulty: 1, word: 'bil',   correct: 'vil',   choices: ['vil',   'hund',  'tre'] },
  { type: 'rhyme', id: 'rhy-004', difficulty: 1, word: 'ball',  correct: 'tall',  choices: ['tall',  'bord',  'stol'] },
  { type: 'rhyme', id: 'rhy-005', difficulty: 1, word: 'sol',   correct: 'stol',   choices: ['stol',   'bok',   'dyr'] },
  // D2
  { type: 'rhyme', id: 'rhy-006', difficulty: 2, word: 'fisk',  correct: 'disk',  choices: ['disk',  'fugl',  'gress'] },
  { type: 'rhyme', id: 'rhy-007', difficulty: 2, word: 'skog',  correct: 'plog',   choices: ['plog',   'is',    'natt'] },
  { type: 'rhyme', id: 'rhy-008', difficulty: 2, word: 'barn',  correct: 'garn',  choices: ['garn',  'fugl',  'tre'] },
  { type: 'rhyme', id: 'rhy-009', difficulty: 2, word: 'natt',  correct: 'matt',  choices: ['matt',  'dag',   'lys'] },
  { type: 'rhyme', id: 'rhy-010', difficulty: 2, word: 'dag',   correct: 'lag',   choices: ['lag',   'natt',  'rom'] },
  // D3
  { type: 'rhyme', id: 'rhy-011', difficulty: 3, word: 'bark', correct: 'mark', choices: ['mark', 'sky',   'blomst'] },
  { type: 'rhyme', id: 'rhy-012', difficulty: 3, word: 'hjerte', correct: 'smerte', choices: ['smerte', 'øye', 'hånd'] },
  { type: 'rhyme', id: 'rhy-013', difficulty: 3, word: 'leke',  correct: 'reke',  choices: ['reke',  'sang',  'bane'] },
  { type: 'rhyme', id: 'rhy-014', difficulty: 3, word: 'vann',  correct: 'mann',  choices: ['mann',  'sky',   'jord'] },
  { type: 'rhyme', id: 'rhy-015', difficulty: 3, word: 'sang',  correct: 'gang',  choices: ['gang',  'lyd',   'bok'] },
  // D4 — 4 choices
  { type: 'rhyme', id: 'rhy-016', difficulty: 4, word: 'sove',  correct: 'love',  choices: ['love',  'spise', 'gå',   'stå'] },
  { type: 'rhyme', id: 'rhy-017', difficulty: 4, word: 'bake',  correct: 'rake',  choices: ['rake',  'synge', 'hoppe', 'løpe'] },
  { type: 'rhyme', id: 'rhy-018', difficulty: 4, word: 'stige', correct: 'seige',  choices: ['seige',  'dale',  'svinge', 'bøye'] },
  { type: 'rhyme', id: 'rhy-019', difficulty: 4, word: 'alle', correct: 'palle', choices: ['palle', 'gulv',  'vegg',  'tak'] },
  { type: 'rhyme', id: 'rhy-020', difficulty: 4, word: 'drøm',  correct: 'strøm', choices: ['strøm', 'tanke', 'farge', 'lyd'] },
  // D5
  { type: 'rhyme', id: 'rhy-021', difficulty: 5, word: 'skrive', correct: 'drive', choices: ['drive', 'synge', 'tegne', 'male'] },
  { type: 'rhyme', id: 'rhy-022', difficulty: 5, word: 'stemme', correct: 'temme', choices: ['temme', 'øyne', 'hender', 'føtter'] },
  { type: 'rhyme', id: 'rhy-023', difficulty: 5, word: 'morgen', correct: 'borgen', choices: ['borgen', 'kveld', 'midnatt', 'grå'] },
  { type: 'rhyme', id: 'rhy-024', difficulty: 5, word: 'fjell',  correct: 'sprell',  choices: ['sprell',  'daler', 'innsjø', 'vann'] },
  { type: 'rhyme', id: 'rhy-025', difficulty: 5, word: 'snø',    correct: 'blø',   choices: ['blø',   'regn',  'sol',   'vind'] },
  // D6
  { type: 'rhyme', id: 'rhy-026', difficulty: 6, word: 'tanke',   correct: 'planke',  choices: ['planke', 'drøm',  'håp',   'frykt'] },
  { type: 'rhyme', id: 'rhy-027', difficulty: 6, word: 'frihet',  correct: 'sannhet',   choices: ['sannhet',  'bundet', 'lenket', 'stengt'] },
  { type: 'rhyme', id: 'rhy-028', difficulty: 6, word: 'lykke',   correct: 'stykke',  choices: ['stykke', 'sorg',  'smerte', 'anger'] },
  { type: 'rhyme', id: 'rhy-029', difficulty: 6, word: 'himmel',  correct: 'svimmel', choices: ['svimmel', 'jord', 'hav',   'stein'] },
  { type: 'rhyme', id: 'rhy-030', difficulty: 6, word: 'klokke',  correct: 'rokke',  choices: ['rokke', 'tid',   'time',  'år'] },
  // D7
  { type: 'rhyme', id: 'rhy-031', difficulty: 7, word: 'vandre',   correct: 'andre',    choices: ['andre',    'dvele',  'streve',  'vente'] },
  { type: 'rhyme', id: 'rhy-032', difficulty: 7, word: 'fortelle', correct: 'novelle', choices: ['novelle', 'lytte',  'skrive',  'lese'] },
  { type: 'rhyme', id: 'rhy-033', difficulty: 7, word: 'minne',    correct: 'finne',    choices: ['finne',    'glemme', 'miste',   'savne'] },
  { type: 'rhyme', id: 'rhy-034', difficulty: 7, word: 'stille',   correct: 'grille',   choices: ['grille',   'bråk',   'lyd',     'rop'] },
  { type: 'rhyme', id: 'rhy-035', difficulty: 7, word: 'glede',    correct: 'rede',     choices: ['rede',     'sorg',   'sinne',   'frykt'] },
  // D8 — the pool used to stop at D7, which made 'rhyme' return null for every
  // round at difficulty 9-10 (getRhymeForDifficulty matches ±1). buildRound then
  // burned attempts on a type that could never resolve and could silently return
  // a short round.
  { type: 'rhyme', id: 'rhy-036', difficulty: 8, word: 'bestemme',  correct: 'hjemme',      choices: ['hjemme',      'borte',    'ute',      'inne'] },
  { type: 'rhyme', id: 'rhy-037', difficulty: 8, word: 'forklare',  correct: 'bevare',      choices: ['bevare',      'forstå',   'spørre',   'lure'] },
  { type: 'rhyme', id: 'rhy-038', difficulty: 8, word: 'begynne',   correct: 'skynne',      choices: ['skynne',      'slutte',   'ende',     'stoppe'] },
  { type: 'rhyme', id: 'rhy-039', difficulty: 8, word: 'oppdage',   correct: 'plage',       choices: ['plage',       'finne',    'miste',    'gjemme'] },
  { type: 'rhyme', id: 'rhy-040', difficulty: 8, word: 'forsvinne', correct: 'vinne',       choices: ['vinne',       'komme',    'vise',     'bli'] },
  // D9
  { type: 'rhyme', id: 'rhy-041', difficulty: 9, word: 'erfaring',   correct: 'forklaring', choices: ['forklaring',  'kunnskap', 'visdom',   'evne'] },
  { type: 'rhyme', id: 'rhy-042', difficulty: 9, word: 'rettferdig', correct: 'verdig',     choices: ['verdig',      'ærlig',    'riktig',   'sann'] },
  { type: 'rhyme', id: 'rhy-043', difficulty: 9, word: 'forsiktig',  correct: 'viktig',     choices: ['viktig',      'nøye',     'trygg',    'rolig'] },
  { type: 'rhyme', id: 'rhy-044', difficulty: 9, word: 'spennende',  correct: 'brennende',  choices: ['brennende',   'kjedelig', 'rolig',    'trist'] },
  { type: 'rhyme', id: 'rhy-045', difficulty: 9, word: 'behandle',   correct: 'forvandle',  choices: ['forvandle',   'ordne',    'styre',    'hjelpe'] },
  // D10
  { type: 'rhyme', id: 'rhy-046', difficulty: 10, word: 'ansvarlig',    correct: 'forsvarlig', choices: ['forsvarlig', 'pliktig',  'streng',    'nøye'] },
  { type: 'rhyme', id: 'rhy-047', difficulty: 10, word: 'nødvendig',    correct: 'innvendig',  choices: ['innvendig',  'viktig',   'unyttig',   'mulig'] },
  { type: 'rhyme', id: 'rhy-048', difficulty: 10, word: 'virkelighet',  correct: 'mulighet',   choices: ['mulighet',   'drøm',     'tanke',     'ønske'] },
  { type: 'rhyme', id: 'rhy-049', difficulty: 10, word: 'forbedring',   correct: 'endring',    choices: ['endring',    'stans',    'tap',       'feil'] },
  { type: 'rhyme', id: 'rhy-050', difficulty: 10, word: 'forundring',   correct: 'undring',    choices: ['undring',    'klarhet',  'visshet',   'sikkerhet'] },

  // ── Utvidelse: 100 flere rim ──
  // D1 — 3 choices
  { type: 'rhyme', id: 'rhy-051', difficulty: 1, word: 'gris',   correct: 'is',    choices: ['is',    'sol',   'bok'] },
  { type: 'rhyme', id: 'rhy-052', difficulty: 1, word: 'dør',    correct: 'gjør',  choices: ['gjør',  'hus',   'tre'] },
  { type: 'rhyme', id: 'rhy-053', difficulty: 1, word: 'stein',  correct: 'bein',  choices: ['bein',  'sol',   'blomst'] },
  { type: 'rhyme', id: 'rhy-054', difficulty: 1, word: 'brød',   correct: 'rød',   choices: ['rød',   'sol',   'katt'] },
  { type: 'rhyme', id: 'rhy-055', difficulty: 1, word: 'sky',    correct: 'by',    choices: ['by',    'hus',   'bil'] },
  { type: 'rhyme', id: 'rhy-056', difficulty: 1, word: 'øre',    correct: 'høre',  choices: ['høre',  'sol',   'bok'] },
  { type: 'rhyme', id: 'rhy-057', difficulty: 1, word: 'ku',     correct: 'du',    choices: ['du',    'hund',  'fugl'] },
  { type: 'rhyme', id: 'rhy-058', difficulty: 1, word: 'hår',    correct: 'år',    choices: ['år',    'sol',   'bok'] },
  { type: 'rhyme', id: 'rhy-059', difficulty: 1, word: 'sau',    correct: 'tau',   choices: ['tau',   'sol',   'bok'] },
  { type: 'rhyme', id: 'rhy-060', difficulty: 1, word: 'te',     correct: 'se',    choices: ['se',    'hund',  'bil'] },
  // D2
  { type: 'rhyme', id: 'rhy-061', difficulty: 2, word: 'strand', correct: 'sand',   choices: ['sand',   'fjord',  'elv'] },
  { type: 'rhyme', id: 'rhy-062', difficulty: 2, word: 'bjørn',  correct: 'ørn',    choices: ['ørn',    'ulv',    'rev'] },
  { type: 'rhyme', id: 'rhy-063', difficulty: 2, word: 'hest',   correct: 'fest',   choices: ['fest',   'sau',    'geit'] },
  { type: 'rhyme', id: 'rhy-064', difficulty: 2, word: 'nese',   correct: 'lese',   choices: ['lese',   'munn',   'øye'] },
  { type: 'rhyme', id: 'rhy-065', difficulty: 2, word: 'sti',    correct: 'ti',     choices: ['ti',     'vei',    'skog'] },
  { type: 'rhyme', id: 'rhy-066', difficulty: 2, word: 'mor',    correct: 'bror',   choices: ['bror',   'far',    'søster'] },
  { type: 'rhyme', id: 'rhy-067', difficulty: 2, word: 'far',    correct: 'har',    choices: ['har',    'mor',    'hus'] },
  { type: 'rhyme', id: 'rhy-068', difficulty: 2, word: 'sommer', correct: 'kommer', choices: ['kommer', 'vinter', 'høst'] },
  { type: 'rhyme', id: 'rhy-069', difficulty: 2, word: 'øye',    correct: 'høye',   choices: ['høye',   'munn',   'hånd'] },
  { type: 'rhyme', id: 'rhy-070', difficulty: 2, word: 'hjul',   correct: 'jul',    choices: ['jul',    'sykkel', 'vogn'] },
  // D3
  { type: 'rhyme', id: 'rhy-071', difficulty: 3, word: 'hopp',  correct: 'kropp', choices: ['kropp', 'løp',    'sprang'] },
  { type: 'rhyme', id: 'rhy-072', difficulty: 3, word: 'hage',  correct: 'lage',  choices: ['lage',  'plante', 'blomst'] },
  { type: 'rhyme', id: 'rhy-073', difficulty: 3, word: 'bade',  correct: 'lade',  choices: ['lade',  'svømme', 'dukke'] },
  { type: 'rhyme', id: 'rhy-074', difficulty: 3, word: 'kaste', correct: 'haste', choices: ['haste', 'løpe',   'hoppe'] },
  { type: 'rhyme', id: 'rhy-075', difficulty: 3, word: 'renne', correct: 'kjenne', choices: ['kjenne', 'løpe',  'sitte'] },
  { type: 'rhyme', id: 'rhy-076', difficulty: 3, word: 'sende', correct: 'hende', choices: ['hende', 'kaste',  'motta'] },
  { type: 'rhyme', id: 'rhy-077', difficulty: 3, word: 'felle', correct: 'telle', choices: ['telle', 'fange',  'jakte'] },
  { type: 'rhyme', id: 'rhy-078', difficulty: 3, word: 'prate', correct: 'late',  choices: ['late',  'tie',    'rope'] },
  { type: 'rhyme', id: 'rhy-079', difficulty: 3, word: 'samle', correct: 'gamle', choices: ['gamle', 'telle',  'sortere'] },
  { type: 'rhyme', id: 'rhy-080', difficulty: 3, word: 'fange', correct: 'lange', choices: ['lange', 'jakte',  'fiske'] },
  // D4 — 4 choices
  { type: 'rhyme', id: 'rhy-081', difficulty: 4, word: 'danse',  correct: 'sjanse',  choices: ['sjanse',  'synge', 'hoppe', 'løpe'] },
  { type: 'rhyme', id: 'rhy-082', difficulty: 4, word: 'synge',  correct: 'tvinge',  choices: ['tvinge',  'danse', 'rope',  'snakke'] },
  { type: 'rhyme', id: 'rhy-083', difficulty: 4, word: 'tenke',  correct: 'senke',   choices: ['senke',   'drømme', 'huske', 'glemme'] },
  { type: 'rhyme', id: 'rhy-084', difficulty: 4, word: 'lytte',  correct: 'flytte',  choices: ['flytte',  'høre',  'se',    'snakke'] },
  { type: 'rhyme', id: 'rhy-085', difficulty: 4, word: 'hoppe',  correct: 'stoppe',  choices: ['stoppe',  'løpe',  'synge', 'danse'] },
  { type: 'rhyme', id: 'rhy-086', difficulty: 4, word: 'male',   correct: 'tale',    choices: ['tale',    'tegne', 'synge', 'bygge'] },
  { type: 'rhyme', id: 'rhy-087', difficulty: 4, word: 'bygge',  correct: 'ligge',   choices: ['ligge',   'male',  'synge', 'hoppe'] },
  { type: 'rhyme', id: 'rhy-088', difficulty: 4, word: 'ringe',  correct: 'springe', choices: ['springe', 'rope',  'synge', 'snakke'] },
  { type: 'rhyme', id: 'rhy-089', difficulty: 4, word: 'klappe', correct: 'snappe',  choices: ['snappe',  'rope',  'synge', 'danse'] },
  { type: 'rhyme', id: 'rhy-090', difficulty: 4, word: 'skrike', correct: 'like',    choices: ['like',    'rope',  'gråte', 'tie'] },
  // D5
  { type: 'rhyme', id: 'rhy-091', difficulty: 5, word: 'stjele', correct: 'dele',   choices: ['dele',   'gjemme', 'finne',  'miste'] },
  { type: 'rhyme', id: 'rhy-092', difficulty: 5, word: 'klage',  correct: 'jage',   choices: ['jage',   'rope',   'gråte',  'smile'] },
  { type: 'rhyme', id: 'rhy-093', difficulty: 5, word: 'spise',  correct: 'vise',   choices: ['vise',   'koke',   'drikke', 'smake'] },
  { type: 'rhyme', id: 'rhy-094', difficulty: 5, word: 'fryse',  correct: 'nyse',   choices: ['nyse',   'varme',  'smelte', 'koke'] },
  { type: 'rhyme', id: 'rhy-095', difficulty: 5, word: 'krype',  correct: 'type',   choices: ['type',   'gå',     'hoppe',  'løpe'] },
  { type: 'rhyme', id: 'rhy-096', difficulty: 5, word: 'undre',  correct: 'hundre', choices: ['hundre', 'tenke',  'lure',   'spørre'] },
  { type: 'rhyme', id: 'rhy-097', difficulty: 5, word: 'kjenne', correct: 'brenne', choices: ['brenne', 'se',     'høre',   'lukte'] },
  { type: 'rhyme', id: 'rhy-098', difficulty: 5, word: 'brette', correct: 'rette',  choices: ['rette',  'folde',  'vaske',  'klippe'] },
  { type: 'rhyme', id: 'rhy-099', difficulty: 5, word: 'styrke', correct: 'dyrke',  choices: ['dyrke',  'svekke', 'bygge',  'trene'] },
  { type: 'rhyme', id: 'rhy-100', difficulty: 5, word: 'gjemme', correct: 'glemme', choices: ['glemme', 'finne',  'søke',   'lete'] },
  // D6
  { type: 'rhyme', id: 'rhy-101', difficulty: 6, word: 'varme',      correct: 'arme',       choices: ['arme',       'kulde',    'kald',     'frost'] },
  { type: 'rhyme', id: 'rhy-102', difficulty: 6, word: 'fare',       correct: 'klare',      choices: ['klare',      'trygghet', 'sikkerhet', 'ro'] },
  { type: 'rhyme', id: 'rhy-103', difficulty: 6, word: 'sorg',       correct: 'torg',       choices: ['torg',       'glede',    'fryd',     'latter'] },
  { type: 'rhyme', id: 'rhy-104', difficulty: 6, word: 'makt',       correct: 'vakt',       choices: ['vakt',       'styre',    'lede',     'herske'] },
  { type: 'rhyme', id: 'rhy-105', difficulty: 6, word: 'enighet',    correct: 'klarhet',    choices: ['klarhet',    'løgn',     'tvil',     'feil'] },
  { type: 'rhyme', id: 'rhy-106', difficulty: 6, word: 'kjærlighet', correct: 'skjønnhet',  choices: ['skjønnhet',  'hat',      'sinne',    'frykt'] },
  { type: 'rhyme', id: 'rhy-107', difficulty: 6, word: 'sterk',      correct: 'verk',       choices: ['verk',       'svak',     'myk',      'mild'] },
  { type: 'rhyme', id: 'rhy-108', difficulty: 6, word: 'rikdom',     correct: 'visdom',     choices: ['visdom',     'fattig',   'kunnskap', 'glede'] },
  { type: 'rhyme', id: 'rhy-109', difficulty: 6, word: 'glans',      correct: 'dans',       choices: ['dans',       'skinn',    'lys',      'farge'] },
  { type: 'rhyme', id: 'rhy-110', difficulty: 6, word: 'kraft',      correct: 'skaft',      choices: ['skaft',      'styrke',   'evne',     'makt'] },
  // D7
  { type: 'rhyme', id: 'rhy-111', difficulty: 7, word: 'beundre',   correct: 'undre',   choices: ['undre',   'forakte', 'avsky',  'ignorere'] },
  { type: 'rhyme', id: 'rhy-112', difficulty: 7, word: 'forstå',    correct: 'få',      choices: ['få',      'tro',     'tvile',  'ane'] },
  { type: 'rhyme', id: 'rhy-113', difficulty: 7, word: 'begripe',   correct: 'gripe',   choices: ['gripe',   'forstå',  'ane',    'skjønne'] },
  { type: 'rhyme', id: 'rhy-114', difficulty: 7, word: 'fortsette', correct: 'sette',   choices: ['sette',   'avslutte', 'stoppe', 'avbryte'] },
  { type: 'rhyme', id: 'rhy-115', difficulty: 7, word: 'skamme',    correct: 'ramme',   choices: ['ramme',   'glede',   'more',   'fryde'] },
  { type: 'rhyme', id: 'rhy-116', difficulty: 7, word: 'fortvile',  correct: 'hvile',   choices: ['hvile',   'glede',   'håpe',   'trøste'] },
  { type: 'rhyme', id: 'rhy-117', difficulty: 7, word: 'beklage',   correct: 'klage',   choices: ['klage',   'glede',   'fryde',  'rose'] },
  { type: 'rhyme', id: 'rhy-118', difficulty: 7, word: 'betale',    correct: 'dale',    choices: ['dale',    'kjøpe',   'selge',  'spare'] },
  { type: 'rhyme', id: 'rhy-119', difficulty: 7, word: 'unngå',     correct: 'nå',      choices: ['nå',      'søke',    'finne',  'oppdage'] },
  { type: 'rhyme', id: 'rhy-120', difficulty: 7, word: 'beskytte',  correct: 'bytte',   choices: ['bytte',   'angripe', 'skade',  'true'] },
  // D8 — 4 choices
  { type: 'rhyme', id: 'rhy-121', difficulty: 8, word: 'anerkjenne',    correct: 'kjenne',   choices: ['kjenne',   'avvise',    'nekte',      'benekte'] },
  { type: 'rhyme', id: 'rhy-122', difficulty: 8, word: 'overvinne',    correct: 'vinne',    choices: ['vinne',    'tape',      'flykte',     'kjempe'] },
  { type: 'rhyme', id: 'rhy-123', difficulty: 8, word: 'gjenoppbygge', correct: 'bygge',    choices: ['bygge',    'rive',      'ødelegge',   'knuse'] },
  { type: 'rhyme', id: 'rhy-124', difficulty: 8, word: 'overbevise',   correct: 'henvise',  choices: ['henvise',  'avsløre',   'skjule',     'lyve'] },
  { type: 'rhyme', id: 'rhy-125', difficulty: 8, word: 'skremme',      correct: 'stemme',   choices: ['stemme',   'glede',     'kjede',      'more'] },
  { type: 'rhyme', id: 'rhy-126', difficulty: 8, word: 'overleve',     correct: 'leve',     choices: ['leve',     'dø',        'forsvinne',  'tape'] },
  { type: 'rhyme', id: 'rhy-127', difficulty: 8, word: 'undersøke',    correct: 'søke',     choices: ['søke',     'finne',     'gjemme',     'unngå'] },
  { type: 'rhyme', id: 'rhy-128', difficulty: 8, word: 'gjenoppta',    correct: 'ta',       choices: ['ta',       'gi',        'la',         'dele'] },
  { type: 'rhyme', id: 'rhy-129', difficulty: 8, word: 'anbefale',     correct: 'befale',   choices: ['befale',   'nekte',     'avvise',     'forby'] },
  { type: 'rhyme', id: 'rhy-130', difficulty: 8, word: 'fortolke',     correct: 'tolke',    choices: ['tolke',    'oversette', 'forstå',     'gjette'] },
  // D9
  { type: 'rhyme', id: 'rhy-131', difficulty: 9, word: 'uavhengig',   correct: 'avhengig',    choices: ['avhengig',    'selvstendig', 'fri',       'bundet'] },
  { type: 'rhyme', id: 'rhy-132', difficulty: 9, word: 'interessant', correct: 'relevant',    choices: ['relevant',    'kjedelig',    'uviktig',   'likegyldig'] },
  { type: 'rhyme', id: 'rhy-133', difficulty: 9, word: 'fantastisk',  correct: 'realistisk',  choices: ['realistisk',  'kjedelig',    'vanlig',    'grei'] },
  { type: 'rhyme', id: 'rhy-134', difficulty: 9, word: 'nysgjerrig',  correct: 'gjerrig',     choices: ['gjerrig',     'sjenert',     'modig',     'snill'] },
  { type: 'rhyme', id: 'rhy-135', difficulty: 9, word: 'imponerende', correct: 'irriterende', choices: ['irriterende', 'kjedelig',    'morsom',    'snill'] },
  { type: 'rhyme', id: 'rhy-136', difficulty: 9, word: 'lykkelig',    correct: 'ulykkelig',   choices: ['ulykkelig',   'glad',        'fornøyd',   'tilfreds'] },
  { type: 'rhyme', id: 'rhy-137', difficulty: 9, word: 'sjenerøs',    correct: 'nervøs',      choices: ['nervøs',      'gjerrig',     'gnien',     'sur'] },
  { type: 'rhyme', id: 'rhy-138', difficulty: 9, word: 'praktisk',    correct: 'dramatisk',   choices: ['dramatisk',   'unyttig',     'komplisert', 'dum'] },
  { type: 'rhyme', id: 'rhy-139', difficulty: 9, word: 'fantasifull', correct: 'smakfull',    choices: ['smakfull',    'kjedelig',    'tam',       'grå'] },
  { type: 'rhyme', id: 'rhy-140', difficulty: 9, word: 'trygghet',    correct: 'ærlighet',    choices: ['ærlighet',    'frykt',       'fare',      'risiko'] },
  // D10
  { type: 'rhyme', id: 'rhy-141', difficulty: 10, word: 'rettferdighet',   correct: 'virkelighet',    choices: ['virkelighet',    'løgn',      'fantasi',    'drøm'] },
  { type: 'rhyme', id: 'rhy-142', difficulty: 10, word: 'tilgjengelighet', correct: 'tydelighet',     choices: ['tydelighet',     'kaos',      'forvirring', 'kompleksitet'] },
  { type: 'rhyme', id: 'rhy-143', difficulty: 10, word: 'selvstendighet',  correct: 'avhengighet',    choices: ['avhengighet',    'styrke',    'makt',       'kontroll'] },
  { type: 'rhyme', id: 'rhy-144', difficulty: 10, word: 'forpliktelse',    correct: 'opplevelse',     choices: ['opplevelse',     'plikt',     'ansvar',     'oppgave'] },
  { type: 'rhyme', id: 'rhy-145', difficulty: 10, word: 'overbevisning',   correct: 'forvisning',     choices: ['forvisning',     'tro',       'tvil',       'mistanke'] },
  { type: 'rhyme', id: 'rhy-146', difficulty: 10, word: 'uavhengighet',    correct: 'vanskelighet',   choices: ['vanskelighet',   'styrke',    'kontroll',   'hjelp'] },
  { type: 'rhyme', id: 'rhy-147', difficulty: 10, word: 'utvikling',       correct: 'forvikling',     choices: ['forvikling',     'forandring', 'vekst',     'fremgang'] },
  { type: 'rhyme', id: 'rhy-148', difficulty: 10, word: 'bevissthet',      correct: 'visshet',        choices: ['visshet',        'tvil',      'uro',        'forvirring'] },
  { type: 'rhyme', id: 'rhy-149', difficulty: 10, word: 'anerkjennelse',   correct: 'erkjennelse',    choices: ['erkjennelse',    'tvil',      'motstand',   'avslag'] },
  { type: 'rhyme', id: 'rhy-150', difficulty: 10, word: 'hjelpeløshet',    correct: 'meningsløshet',  choices: ['meningsløshet',  'styrke',    'håp',        'kontroll'] },
]

export function getRhymeForDifficulty(difficulty: number): RhymeQuestion[] {
  return rhymeQuestions.filter(q => Math.abs(q.difficulty - difficulty) <= 1)
}
