import type { Word } from './types'

/**
 * Word pool exclusively for spell_it questions (difficulty 5–10).
 * These words are chosen for spelling-practice value — Norwegian words kids
 * encounter at school but may misspell.
 */
export const spellWords: Word[] = [

  // ── Dyr / Animals ─────────────────────────────────────────────────────────
  { id: 'sw-dyr-001', word: 'svane',        emoji: '🦢', category: 'dyr',     difficulty: 5  },
  { id: 'sw-dyr-002', word: 'ugle',         emoji: '🦉', category: 'dyr',     difficulty: 5  },
  { id: 'sw-dyr-003', word: 'elg',          emoji: '🦌', category: 'dyr',     difficulty: 5  },
  { id: 'sw-dyr-004', word: 'bever',        emoji: '🦫', category: 'dyr',     difficulty: 5  },
  { id: 'sw-dyr-005', word: 'kanin',        emoji: '🐰', category: 'dyr',     difficulty: 5  },
  { id: 'sw-dyr-006', word: 'ørn',          emoji: '🦅', category: 'dyr',     difficulty: 5  },
  { id: 'sw-dyr-007', word: 'hval',         emoji: '🐋', category: 'dyr',     difficulty: 5  },
  { id: 'sw-dyr-008', word: 'frosk',        emoji: '🐸', category: 'dyr',     difficulty: 5  },
  { id: 'sw-dyr-009', word: 'maur',         emoji: '🐜', category: 'dyr',     difficulty: 5  },
  { id: 'sw-dyr-010', word: 'hjort',        emoji: '🦌', category: 'dyr',     difficulty: 5  },
  { id: 'sw-dyr-011', word: 'gaupe',        emoji: '🐆', category: 'dyr',     difficulty: 6  },
  { id: 'sw-dyr-012', word: 'delfin',       emoji: '🐬', category: 'dyr',     difficulty: 6  },
  { id: 'sw-dyr-013', word: 'isbjørn',      emoji: '🐻‍❄️', category: 'dyr',  difficulty: 6  },
  { id: 'sw-dyr-014', word: 'flamingo',     emoji: '🦩', category: 'dyr',     difficulty: 7  },
  { id: 'sw-dyr-015', word: 'krabbe',       emoji: '🦀', category: 'dyr',     difficulty: 6  },
  { id: 'sw-dyr-016', word: 'hummer',       emoji: '🦞', category: 'dyr',     difficulty: 6  },
  { id: 'sw-dyr-017', word: 'skilpadde',    emoji: '🐢', category: 'dyr',     difficulty: 8  },
  { id: 'sw-dyr-018', word: 'pinnsvin',     emoji: '🦔', category: 'dyr',     difficulty: 7  },
  { id: 'sw-dyr-019', word: 'papegøye',     emoji: '🦜', category: 'dyr',     difficulty: 8  },
  { id: 'sw-dyr-020', word: 'blekksprut',   emoji: '🦑', category: 'dyr',     difficulty: 8  },
  { id: 'sw-dyr-021', word: 'edderkopp',    emoji: '🕷️', category: 'dyr',    difficulty: 9  },
  { id: 'sw-dyr-022', word: 'sommerfugl',   emoji: '🦋', category: 'dyr',     difficulty: 9  },
  { id: 'sw-dyr-023', word: 'meitemark',    emoji: '🪱', category: 'dyr',     difficulty: 9  },
  { id: 'sw-dyr-024', word: 'broddsverm',   emoji: '🐝', category: 'dyr',     difficulty: 10 },
  { id: 'sw-dyr-025', word: 'gresshoppe',   emoji: '🦗', category: 'dyr',     difficulty: 8  },
  { id: 'sw-dyr-026', word: 'slange',       emoji: '🐍', category: 'dyr',     difficulty: 6  },
  { id: 'sw-dyr-027', word: 'orm',          emoji: '🪱', category: 'dyr',     difficulty: 5  },
  { id: 'sw-dyr-028', word: 'ekorn',        emoji: '🐿️', category: 'dyr',    difficulty: 6  },
  { id: 'sw-dyr-029', word: 'mink',         emoji: '🦦', category: 'dyr',     difficulty: 5  },
  { id: 'sw-dyr-030', word: 'oter',         emoji: '🦦', category: 'dyr',     difficulty: 5  },
  { id: 'sw-dyr-031', word: 'villsvin',     emoji: '🐗', category: 'dyr',     difficulty: 7  },
  { id: 'sw-dyr-032', word: 'gepard',       emoji: '🐆', category: 'dyr',     difficulty: 7  },
  { id: 'sw-dyr-033', word: 'leopard',      emoji: '🐆', category: 'dyr',     difficulty: 7  },
  { id: 'sw-dyr-034', word: 'sjøhest',      emoji: '🐴', category: 'dyr',     difficulty: 7  },
    { id: 'sw-dyr-035', word: 'pelikaner', emoji: '🦢', category: 'dyr', difficulty: 9 },
  
    // -- Smiley / Emotions ─────────────────────────────────────────────────────────────
    { id: 'sw-smi-001', word: 'glad', emoji: '😀', category: 'smiley', difficulty: 5 },
    { id: 'sw-smi-002', word: 'trist', emoji: '😢', category: 'smiley', difficulty: 5 },
    { id: 'sw-smi-003', word: 'sint', emoji: '😠', category: 'smiley', difficulty: 5 },
    { id: 'sw-smi-004', word: 'overrasket', emoji: '😲', category: 'smiley', difficulty: 6 },
    { id: 'sw-smi-005', word: 'skuffet', emoji: '😞', category: 'smiley', difficulty: 6 },
    { id: 'sw-smi-006', word: 'forvirret', emoji: '😕', category: 'smiley', difficulty: 6 },
    { id: 'sw-smi-007', word: 'stolt', emoji: '😌', category: 'smiley', difficulty: 7 },
    { id: 'sw-smi-008', word: 'redd', emoji: '😨', category: 'smiley', difficulty: 7 },
    { id: 'sw-smi-009', word: 'lei seg', emoji: '😔', category: 'smiley', difficulty: 7 },
    { id: 'sw-smi-010', word: 'fornøyd', emoji: '😊', category: 'smiley', difficulty: 5 },
    { id: 'sw-smi-011', word: 'latter', emoji: '🤣', category: 'smiley', difficulty: 6 },
    { id: 'sw-smi-012', word: 'kjempeglad', emoji: '🤩', category: 'smiley', difficulty: 7 },
    { id: 'sw-smi-013', word: 'smile', emoji: '😊', category: 'smiley', difficulty: 5 },
    { id: 'sw-smi-014', word: 'OK', emoji: '👌', category: 'smiley', difficulty: 5 },
    { id: 'sw-smi-015', word: 'pengesekk', emoji: '💰', category: 'smiley', difficulty: 5 },
    { id: 'sw-smi-016', word: 'solbriller', emoji: '😎', category: 'smiley', difficulty: 5 },
    { id: 'sw-smi-017', word: 'glovarm', emoji: '🥵', category: 'smiley', difficulty: 6 },
    { id: 'sw-smi-018', word: 'termometer', emoji: '🌡️', category: 'smiley', difficulty: 7 },
    { id: 'sw-smi-019', word: 'stetoskop', emoji: '🩺', category: 'smiley', difficulty: 7 },
    { id: 'sw-smi-020', word: 'kvalm', emoji: '🤢', category: 'smiley', difficulty: 7 },
    { id: 'sw-smi-021', word: 'feiring', emoji: '🥳', category: 'smiley', difficulty: 7 },
    { id: 'sw-smi-022', word: 'forvirret', emoji: '🥴', category: 'smiley', difficulty: 7 },
    { id: 'sw-smi-023', word: 'uvel', emoji: '🤒', category: 'smiley', difficulty: 7 },
    { id: 'sw-smi-024', word: 'crazy', emoji: '🤪', category: 'smiley', difficulty: 7 },
    { id: 'sw-smi-025', word: 'sint', emoji: '🤬', category: 'smiley', difficulty: 7 },
    { id: 'sw-smi-026', word: 'hodeskalle', emoji: '💀', category: 'smiley', difficulty: 7 },
    { id: 'sw-smi-027', word: 'spøkelse', emoji: '👻', category: 'smiley', difficulty: 7 },
    { id: 'sw-smi-028', word: 'robot', emoji: '🤖', category: 'smiley', difficulty: 7 },

    // add 40 more from here https://emojipedia.org/objects that are not amigous and not already in this file
    { id: 'sw-obj-001', word: 'timeglass',       emoji: '⏳', category: 'objekt', difficulty: 6 },
    { id: 'sw-obj-002', word: 'nøkkel',          emoji: '🔑', category: 'objekt', difficulty: 5 },
    { id: 'sw-obj-003', word: 'binders',         emoji: '📎', category: 'objekt', difficulty: 5 },
    { id: 'sw-obj-004', word: 'saks',            emoji: '✂️', category: 'objekt', difficulty: 5 },
    { id: 'sw-obj-005', word: 'lås',             emoji: '🔒', category: 'objekt', difficulty: 6 },
    { id: 'sw-obj-006', word: 'verktøykasse',    emoji: '🧰', category: 'objekt', difficulty: 7 },
    { id: 'sw-obj-007', word: 'hammer',          emoji: '🔨', category: 'objekt', difficulty: 6 },
    { id: 'sw-obj-008', word: 'skiftenøkkel',    emoji: '🔧', category: 'objekt', difficulty: 8 },
    { id: 'sw-obj-009', word: 'magnet',          emoji: '🧲', category: 'objekt', difficulty: 7 },
    { id: 'sw-obj-010', word: 'skrutrekker',     emoji: '🪛', category: 'objekt', difficulty: 8 },
    { id: 'sw-obj-011', word: 'sikkerhetsnål',   emoji: '🧷', category: 'objekt', difficulty: 6 },
    { id: 'sw-obj-012', word: 'tryllestav',      emoji: '🪄', category: 'objekt', difficulty: 9 },
    { id: 'sw-obj-013', word: 'reagensrør',      emoji: '🧪', category: 'objekt', difficulty: 9 },
    { id: 'sw-obj-014', word: 'petri-skål',      emoji: '🧫', category: 'objekt', difficulty: 10 },
    { id: 'sw-obj-015', word: 'brannslukker',    emoji: '🧯', category: 'objekt', difficulty: 8 },
    { id: 'sw-obj-016', word: 'skjold',          emoji: '🛡️', category: 'objekt', difficulty: 7 },
    { id: 'sw-obj-017', word: 'murstein',        emoji: '🧱', category: 'objekt', difficulty: 8 },
    { id: 'sw-obj-018', word: 'tråd',            emoji: '🧵', category: 'objekt', difficulty: 6 },
    { id: 'sw-obj-019', word: 'toalettpapir',    emoji: '🧻', category: 'objekt', difficulty: 5 },
    { id: 'sw-obj-020', word: 'søppelbøtte',     emoji: '🗑️', category: 'objekt', difficulty: 5 },
    { id: 'sw-obj-021', word: 'kompass',         emoji: '🧭', category: 'objekt', difficulty: 7 },
    { id: 'sw-obj-022', word: 'kvittering',      emoji: '🧾', category: 'objekt', difficulty: 9 },
    { id: 'sw-obj-023', word: 'eske',            emoji: '📦', category: 'objekt', difficulty: 6 },
    { id: 'sw-obj-024', word: 'batteri',         emoji: '🔋', category: 'objekt', difficulty: 6 },
    { id: 'sw-obj-025', word: 'støpsel',         emoji: '🔌', category: 'objekt', difficulty: 7 },
    { id: 'sw-obj-026', word: 'lyspære',         emoji: '💡', category: 'objekt', difficulty: 5 },
    { id: 'sw-obj-027', word: 'lommelykt',       emoji: '🔦', category: 'objekt', difficulty: 7 },
    { id: 'sw-obj-028', word: 'lys',             emoji: '🕯️', category: 'objekt', difficulty: 6 },
    { id: 'sw-obj-029', word: 'teddybjørn',      emoji: '🧸', category: 'objekt', difficulty: 6 },
    { id: 'sw-obj-030', word: 'gave',            emoji: '🎁', category: 'objekt', difficulty: 5 },
    { id: 'sw-obj-031', word: 'ballong',         emoji: '🎈', category: 'objekt', difficulty: 5 },
    { id: 'sw-obj-032', word: 'bøtte',           emoji: '🪣', category: 'objekt', difficulty: 7 },
    { id: 'sw-obj-033', word: 'vaskekurv',       emoji: '🧺', category: 'objekt', difficulty: 6 },
    { id: 'sw-obj-034', word: 'såpe',            emoji: '🧼', category: 'objekt', difficulty: 5 },
    { id: 'sw-obj-035', word: 'svamp',           emoji: '🧽', category: 'objekt', difficulty: 6 },
    { id: 'sw-obj-036', word: 'barberhøvel',     emoji: '🪒', category: 'objekt', difficulty: 8 },
    { id: 'sw-obj-037', word: 'puslespillbrikke',emoji: '🧩', category: 'objekt', difficulty: 8 },
    { id: 'sw-obj-038', word: 'vinkelmåler',     emoji: '📐', category: 'objekt', difficulty: 7 },
    { id: 'sw-obj-039', word: 'penn',            emoji: '🖊️', category: 'objekt', difficulty: 5 },
    { id: 'sw-obj-040', word: 'puslespill',      emoji: '🧩', category: 'objekt', difficulty: 9 },

    { id: 'sw-obj-041', word: 'handlevogn',      emoji: '🛒', category: 'objekt', difficulty: 5 },
    { id: 'sw-obj-042', word: 'handleposer',     emoji: '🛍️', category: 'objekt', difficulty: 5 },
    { id: 'sw-obj-043', word: 'skriver',         emoji: '🖨️', category: 'objekt', difficulty: 7 },
    { id: 'sw-obj-044', word: 'kamera',          emoji: '📷', category: 'objekt', difficulty: 6 },
    { id: 'sw-obj-045', word: 'videokamera',     emoji: '🎥', category: 'objekt', difficulty: 7 },
    { id: 'sw-obj-046', word: 'radio',           emoji: '📻', category: 'objekt', difficulty: 6 },
    { id: 'sw-obj-047', word: 'fjernsyn',        emoji: '📺', category: 'objekt', difficulty: 6 },
    { id: 'sw-obj-048', word: 'mobil',           emoji: '📱', category: 'objekt', difficulty: 5 },
    { id: 'sw-obj-049', word: 'spillkontroll',   emoji: '🎮', category: 'objekt', difficulty: 7 },
    { id: 'sw-obj-050', word: 'veggklokke',      emoji: '🕰️', category: 'objekt', difficulty: 6 },
    { id: 'sw-obj-051', word: 'notatblokk',      emoji: '🗒️', category: 'objekt', difficulty: 5 },
    { id: 'sw-obj-052', word: 'kalender',        emoji: '📆', category: 'objekt', difficulty: 6 },
    { id: 'sw-obj-053', word: 'amulet',          emoji: '🧿', category: 'objekt', difficulty: 9 },
    { id: 'sw-obj-054', word: 'matryoshka',      emoji: '🪆', category: 'objekt', difficulty: 9 },
    { id: 'sw-obj-055', word: 'rød konvolutt',   emoji: '🧧', category: 'objekt', difficulty: 8 },
    { id: 'sw-obj-056', word: 'fyrverkeri',      emoji: '🧨', category: 'objekt', difficulty: 7 },
    { id: 'sw-obj-057', word: 'oljelampe',       emoji: '🪔', category: 'objekt', difficulty: 8 },
    { id: 'sw-obj-058', word: 'øks',             emoji: '🪓', category: 'objekt', difficulty: 7 },
    { id: 'sw-obj-059', word: 'verktøysett',     emoji: '🛠️', category: 'objekt', difficulty: 8 },
    { id: 'sw-obj-060', word: 'dna',             emoji: '🧬', category: 'objekt', difficulty: 10 },
    { id: 'sw-obj-061', word: 'bilde',           emoji: '🖼️', category: 'objekt', difficulty: 6 },
    { id: 'sw-obj-062', word: 'skilt',           emoji: '🪧', category: 'objekt', difficulty: 6 },
    { id: 'sw-obj-063', word: 'vindu',           emoji: '🪟', category: 'objekt', difficulty: 5 },
    { id: 'sw-obj-064', word: 'speil',           emoji: '🪞', category: 'objekt', difficulty: 6 },
    { id: 'sw-obj-065', word: 'sikkerhetsvest',  emoji: '🦺', category: 'objekt', difficulty: 7 },
    { id: 'sw-obj-066', word: 'musefelle',       emoji: '🪤', category: 'objekt', difficulty: 9 },
    { id: 'sw-obj-067', word: 'faks',            emoji: '📠', category: 'objekt', difficulty: 9 },
    { id: 'sw-obj-068', word: 'valgurne',        emoji: '🗳️', category: 'objekt', difficulty: 9 },
    { id: 'sw-obj-069', word: 'bjelle',          emoji: '🛎️', category: 'objekt', difficulty: 7 },
    { id: 'sw-obj-070', word: 'anker',           emoji: '⚓', category: 'objekt', difficulty: 7 },
    { id: 'sw-obj-071', word: 'koffert',         emoji: '🧳', category: 'objekt', difficulty: 6 },
    { id: 'sw-obj-072', word: 'ved',             emoji: '🪵', category: 'objekt', difficulty: 7 },
    { id: 'sw-obj-073', word: 'megafon',         emoji: '📣', category: 'objekt', difficulty: 6 },
    { id: 'sw-obj-074', word: 'fasttelefon',     emoji: '☎️', category: 'objekt', difficulty: 6 },
    { id: 'sw-obj-075', word: 'gammelnøkkel',    emoji: '🗝️', category: 'objekt', difficulty: 7 },
    { id: 'sw-obj-076', word: 'mikser',          emoji: '🎛️', category: 'objekt', difficulty: 9 },
    { id: 'sw-obj-077', word: 'mynt',            emoji: '🪙', category: 'objekt', difficulty: 6 },
    { id: 'sw-obj-078', word: 'minnebrikke',     emoji: '💾', category: 'objekt', difficulty: 7 },
    { id: 'sw-obj-079', word: 'lysestake',       emoji: '🕯️', category: 'objekt', difficulty: 6 },
    { id: 'sw-obj-080', word: 'høyttaler',       emoji: '🔊', category: 'objekt', difficulty: 6 },


  // ── Natur / Nature ────────────────────────────────────────────────────────
  { id: 'sw-nat-001', word: 'fjell',        emoji: '🏔️', category: 'natur',   difficulty: 5  },
  { id: 'sw-nat-002', word: 'blomst',       emoji: '🌸', category: 'natur',   difficulty: 6  },
  { id: 'sw-nat-003', word: 'storm',        emoji: '🌩️', category: 'natur',  difficulty: 5  },
  { id: 'sw-nat-004', word: 'isklump',        emoji: '🧊', category: 'natur',   difficulty: 6  },
  { id: 'sw-nat-005', word: 'vulkan',       emoji: '🌋', category: 'natur',   difficulty: 6  },
  { id: 'sw-nat-006', word: 'ørken',        emoji: '🏜️', category: 'natur',  difficulty: 6  },
  { id: 'sw-nat-007', word: 'palme',       emoji: '🌴', category: 'natur',   difficulty: 6  },
  { id: 'sw-nat-008', word: 'strand',       emoji: '🏖️', category: 'natur',  difficulty: 6  },
  { id: 'sw-nat-009', word: 'klippe',       emoji: '🪨', category: 'natur',   difficulty: 6  },
  
  { id: 'sw-nat-011', word: 'grein',     emoji: '🌿', category: 'natur',   difficulty: 7  },
  { id: 'sw-nat-012', word: 'brann',    emoji: '🔥', category: 'natur',   difficulty: 8  },
  { id: 'sw-nat-013', word: 'tordenvær',    emoji: '⛈️', category: 'natur',  difficulty: 8  },
  { id: 'sw-nat-014', word: 'regnbue',      emoji: '🌈', category: 'natur',   difficulty: 7  },
  { id: 'sw-nat-015', word: 'nordlys',      emoji: '🌌', category: 'natur',   difficulty: 7  },
  { id: 'sw-nat-016', word: 'vanndråpe',     emoji: '💧', category: 'natur',   difficulty: 7  },
  { id: 'sw-nat-017', word: 'innsjø',       emoji: '🏞️', category: 'natur',  difficulty: 6  },
  { id: 'sw-nat-018', word: 'grotte',       emoji: '🕳️', category: 'natur',  difficulty: 6  },

  // ── Mat / Food ────────────────────────────────────────────────────────────
  { id: 'sw-mat-001', word: 'suppe',        emoji: '🍲', category: 'mat',     difficulty: 5  },
  { id: 'sw-mat-002', word: 'salat',        emoji: '🥗', category: 'mat',     difficulty: 5  },
  { id: 'sw-mat-003', word: 'kylling',      emoji: '🍗', category: 'mat',     difficulty: 6  },
  { id: 'sw-mat-004', word: 'laks',         emoji: '🐟', category: 'mat',     difficulty: 5  },
  { id: 'sw-mat-005', word: 'reker',        emoji: '🍤', category: 'mat',     difficulty: 5  },
  { id: 'sw-mat-006', word: 'potet',        emoji: '🥔', category: 'mat',     difficulty: 5  },
  { id: 'sw-mat-007', word: 'gulrot',       emoji: '🥕', category: 'mat',     difficulty: 6  },
  { id: 'sw-mat-008', word: 'agurk',        emoji: '🥒', category: 'mat',     difficulty: 5  },
  { id: 'sw-mat-009', word: 'tomat',        emoji: '🍅', category: 'mat',     difficulty: 5  },
  { id: 'sw-mat-010', word: 'paprika',      emoji: '🫑', category: 'mat',     difficulty: 7  },
  { id: 'sw-mat-011', word: 'avokado',      emoji: '🥑', category: 'mat',     difficulty: 7  },
  { id: 'sw-mat-012', word: 'bringebær',    emoji: '🫐', category: 'mat',     difficulty: 8  },
  { id: 'sw-mat-013', word: 'fersken',      emoji: '🍑', category: 'mat',     difficulty: 7  },
  { id: 'sw-mat-014', word: 'mango',        emoji: '🥭', category: 'mat',     difficulty: 5  },
  { id: 'sw-mat-015', word: 'kiwi',         emoji: '🥝', category: 'mat',     difficulty: 5  },
  { id: 'sw-mat-016', word: 'bank',     emoji: '🏦', category: 'mat',     difficulty: 8  },
  { id: 'sw-mat-017', word: 'sitron',       emoji: '🍋', category: 'mat',     difficulty: 6  },
  { id: 'sw-mat-018', word: 'hvitløk',      emoji: '🧄', category: 'mat',     difficulty: 7  },
  { id: 'sw-mat-019', word: 'løk',          emoji: '🧅', category: 'mat',     difficulty: 5  },
  { id: 'sw-mat-020', word: 'sopp',         emoji: '🍄', category: 'mat',     difficulty: 5  },
  { id: 'sw-mat-021', word: 'blomkål',      emoji: '🥦', category: 'mat',     difficulty: 7  },
  { id: 'sw-mat-023', word: 'vafler',       emoji: '🧇', category: 'mat',     difficulty: 6  },
  { id: 'sw-mat-024', word: 'pannekake',    emoji: '🥞', category: 'mat',     difficulty: 8  },
  { id: 'sw-mat-025', word: 'is',           emoji: '🍦', category: 'mat',     difficulty: 5  },
  { id: 'sw-mat-026', word: 'iskrem',       emoji: '🍨', category: 'mat',     difficulty: 6  },
  { id: 'sw-mat-027', word: 'godteri',      emoji: '🍬', category: 'mat',     difficulty: 7  },
  { id: 'sw-mat-028', word: 'slikkepott',   emoji: '🍭', category: 'mat',     difficulty: 10 },
  { id: 'sw-mat-029', word: 'kjeks',        emoji: '🍪', category: 'mat',     difficulty: 5  },
  { id: 'sw-mat-030', word: 'kake',         emoji: '🎂', category: 'mat',     difficulty: 5  },

  // ── Hjem / Home ───────────────────────────────────────────────────────────
  { id: 'sw-hje-001', word: 'trapp',        emoji: '🪜', category: 'hjem',    difficulty: 5  },
  { id: 'sw-hje-002', word: 'kjøkken',      emoji: '🍳', category: 'hjem',    difficulty: 7  },
  { id: 'sw-hje-003', word: 'soverom',      emoji: '🛏️', category: 'hjem',   difficulty: 7  },
  { id: 'sw-hje-004', word: 'baderom',      emoji: '🚿', category: 'hjem',    difficulty: 7  },
  { id: 'sw-hje-005', word: 'stue',         emoji: '🛋️', category: 'hjem',   difficulty: 5  },
  { id: 'sw-hje-006', word: 'garasje',      emoji: '🏠', category: 'hjem',    difficulty: 7  },
  { id: 'sw-hje-007', word: 'hytte',        emoji: '🏕️', category: 'hjem',   difficulty: 5  },
  { id: 'sw-hje-008', word: 'veranda',      emoji: '🏡', category: 'hjem',    difficulty: 7  },
  { id: 'sw-hje-009', word: 'plen',         emoji: '🌱', category: 'hjem',    difficulty: 5  },
  { id: 'sw-hje-010', word: 'stol',      emoji: '🪑', category: 'hjem',    difficulty: 7  },
  { id: 'sw-hje-011', word: 'kjøleskap',    emoji: '🥶', category: 'hjem',    difficulty: 9  },
  { id: 'sw-hje-012', word: 'oppvaskmaskin',emoji: '🫧', category: 'hjem',    difficulty: 10 },
  { id: 'sw-hje-013', word: 'vaskemaskin',  emoji: '🫧', category: 'hjem',    difficulty: 10 },
  { id: 'sw-hje-014', word: 'pute',         emoji: '🛏️', category: 'hjem',   difficulty: 5  },
  { id: 'sw-hje-015', word: 'teppe',        emoji: '🧶', category: 'hjem',    difficulty: 5  },

  // ── Skole / School ────────────────────────────────────────────────────────
  { id: 'sw-sko-001', word: 'blyant',       emoji: '✏️', category: 'skole',  difficulty: 6  },
  { id: 'sw-sko-003', word: 'linjal',       emoji: '📏', category: 'skole',   difficulty: 6  },
  { id: 'sw-sko-004', word: 'kalkulator',   emoji: '🧮', category: 'skole',  difficulty: 9  },
  { id: 'sw-sko-005', word: 'geografi',     emoji: '🗺️', category: 'skole', difficulty: 9  },
  { id: 'sw-sko-006', word: 'matematikk',   emoji: '🔢', category: 'skole',  difficulty: 10 },
  { id: 'sw-sko-007', word: 'bibliotek',    emoji: '📚', category: 'skole',  difficulty: 9  },
  { id: 'sw-sko-009', word: 'ryggsekk',     emoji: '🎒', category: 'skole',   difficulty: 8  },
  { id: 'sw-sko-010', word: 'bok',          emoji: '📖', category: 'skole',   difficulty: 5  },
  { id: 'sw-sko-011', word: 'hefte',         emoji: '📓', category: 'skole',   difficulty: 5  },
  { id: 'sw-sko-012', word: 'friminutt',    emoji: '⏰', category: 'skole',   difficulty: 9  },
  { id: 'sw-sko-013', word: 'lærer',        emoji: '👨‍🏫', category: 'skole', difficulty: 6  },
  { id: 'sw-sko-014', word: 'elev',         emoji: '🧒', category: 'skole',   difficulty: 5  },
  { id: 'sw-sko-015', word: 'lekse',        emoji: '📝', category: 'skole',   difficulty: 6  },
  { id: 'sw-sko-016', word: 'prøve',        emoji: '📝', category: 'skole',   difficulty: 6  },
  { id: 'sw-sko-017', word: 'karakter',     emoji: '⭐', category: 'skole',   difficulty: 8  },
  { id: 'sw-sko-018', word: 'naturfag',     emoji: '🔬', category: 'skole',   difficulty: 8  },
  { id: 'sw-sko-019', word: 'norsk',        emoji: '🇳🇴', category: 'skole', difficulty: 5  },
  { id: 'sw-sko-020', word: 'engelsk',      emoji: '🇬🇧', category: 'skole', difficulty: 7  },

  // ── Sport / Sport ─────────────────────────────────────────────────────────
  { id: 'sw-spo-001', word: 'fotball',      emoji: '⚽', category: 'sport',  difficulty: 7  },
  { id: 'sw-spo-002', word: 'basket',       emoji: '🏀', category: 'sport',  difficulty: 6  },
  { id: 'sw-spo-003', word: 'svømming',     emoji: '🏊', category: 'sport',  difficulty: 7  },
  { id: 'sw-spo-004', word: 'langrenn',     emoji: '⛷️', category: 'sport', difficulty: 7  },
  { id: 'sw-spo-005', word: 'slalåm',       emoji: '🎿', category: 'sport',  difficulty: 7  },
  { id: 'sw-spo-006', word: 'ski',          emoji: '🎿', category: 'sport',  difficulty: 5  },
  { id: 'sw-spo-007', word: 'hoppe',        emoji: '🤸', category: 'sport',  difficulty: 6  },
  { id: 'sw-spo-008', word: 'løping',       emoji: '🏃', category: 'sport',  difficulty: 7  },
  { id: 'sw-spo-009', word: 'sykling',      emoji: '🚴', category: 'sport',  difficulty: 7  },
  { id: 'sw-spo-010', word: 'klatring',     emoji: '🧗', category: 'sport',  difficulty: 8  },
  { id: 'sw-spo-011', word: 'friidrett',    emoji: '🏅', category: 'sport',  difficulty: 8  },
  { id: 'sw-spo-012', word: 'håndball',     emoji: '🤾', category: 'sport',  difficulty: 8  },
  { id: 'sw-spo-013', word: 'volleyball',   emoji: '🏐', category: 'sport',  difficulty: 9  },
  { id: 'sw-spo-014', word: 'bordtennis',   emoji: '🏓', category: 'sport',  difficulty: 9  },
  { id: 'sw-spo-015', word: 'badminton',    emoji: '🏸', category: 'sport',  difficulty: 9  },

  // ── Kropp / Body ──────────────────────────────────────────────────────────
  { id: 'sw-kro-001', word: 'skulder',      emoji: '💪', category: 'kropp',  difficulty: 7  },
  { id: 'sw-kro-002', word: 'nakke',        emoji: '🦴', category: 'kropp',  difficulty: 5  },
  { id: 'sw-kro-003', word: 'panne',        emoji: '🧠', category: 'kropp',  difficulty: 5  },
  { id: 'sw-kro-004', word: 'kinn',         emoji: '😊', category: 'kropp',  difficulty: 5  },
  { id: 'sw-kro-005', word: 'tenner',       emoji: '🦷', category: 'kropp',  difficulty: 6  },
  { id: 'sw-kro-006', word: 'tunge',        emoji: '👅', category: 'kropp',  difficulty: 6  },
  { id: 'sw-kro-007', word: 'hals',         emoji: '🦴', category: 'kropp',  difficulty: 5  },
  { id: 'sw-kro-008', word: 'rygg',         emoji: '🏃', category: 'kropp',  difficulty: 5  },
  { id: 'sw-kro-009', word: 'finger',       emoji: '☝️', category: 'kropp',  difficulty: 6  },
  { id: 'sw-kro-010', word: 'tommel',       emoji: '👍', category: 'kropp',  difficulty: 6  },
  { id: 'sw-kro-011', word: 'legg',         emoji: '🦵', category: 'kropp',  difficulty: 5  },
  { id: 'sw-kro-012', word: 'hofte',        emoji: '🕺', category: 'kropp',  difficulty: 6  },

  // ── Farge / Colors ────────────────────────────────────────────────────────
  { id: 'sw-far-001', word: 'rød',          emoji: '🔴', category: 'farge',  difficulty: 5  },
  { id: 'sw-far-002', word: 'blå',          emoji: '🔵', category: 'farge',  difficulty: 5  },
  { id: 'sw-far-003', word: 'grønn',        emoji: '🟢', category: 'farge',  difficulty: 5  },
  { id: 'sw-far-004', word: 'gul',          emoji: '🟡', category: 'farge',  difficulty: 5  },
  { id: 'sw-far-005', word: 'hvit',         emoji: '⬜', category: 'farge',  difficulty: 5  },
  { id: 'sw-far-006', word: 'svart',        emoji: '⬛', category: 'farge',  difficulty: 5  },
  { id: 'sw-far-007', word: 'oransje',      emoji: '🟠', category: 'farge',  difficulty: 7  },
  { id: 'sw-far-008', word: 'lilla',        emoji: '🟣', category: 'farge',  difficulty: 5  },
  { id: 'sw-far-009', word: 'rosa',         emoji: '🩷', category: 'farge',  difficulty: 5  },
  { id: 'sw-far-010', word: 'brun',         emoji: '🟤', category: 'farge',  difficulty: 5  },
  { id: 'sw-far-011', word: 'turkis',       emoji: '🩵', category: 'farge',  difficulty: 7  },
  { id: 'sw-far-012', word: 'beige',        emoji: '🟫', category: 'farge',  difficulty: 6  },
  { id: 'sw-far-013', word: 'sølv',         emoji: '🥈', category: 'farge',  difficulty: 6  },
  { id: 'sw-far-014', word: 'gull',         emoji: '🥇', category: 'farge',  difficulty: 5  },

  // ── Yrker / Professions ───────────────────────────────────────────────────
  { id: 'sw-yke-001', word: 'lege',         emoji: '👨‍⚕️', category: 'yrke', difficulty: 5  },
  { id: 'sw-yke-002', word: 'tannlege',     emoji: '🦷', category: 'yrke',   difficulty: 8  },
  { id: 'sw-yke-003', word: 'baker',        emoji: '🥐', category: 'yrke',   difficulty: 5  },
  { id: 'sw-yke-004', word: 'brannmann',    emoji: '👨‍🚒', category: 'yrke', difficulty: 9  },
  { id: 'sw-yke-005', word: 'politi',       emoji: '👮', category: 'yrke',   difficulty: 6  },
  { id: 'sw-yke-006', word: 'pilot',        emoji: '✈️', category: 'yrke',  difficulty: 5  },
  { id: 'sw-yke-007', word: 'kokk',         emoji: '👨‍🍳', category: 'yrke', difficulty: 5  },
  { id: 'sw-yke-008', word: 'ingeniør',     emoji: '⚙️', category: 'yrke',  difficulty: 8  },
  { id: 'sw-yke-009', word: 'sykepleier',   emoji: '💉', category: 'yrke',   difficulty: 9  },
  { id: 'sw-yke-010', word: 'arkitekt',     emoji: '🏛️', category: 'yrke',  difficulty: 8  },
  { id: 'sw-yke-011', word: 'astronaut',    emoji: '👨‍🚀', category: 'yrke', difficulty: 9  },
  { id: 'sw-yke-012', word: 'forsker',      emoji: '🔬', category: 'yrke',   difficulty: 7  },

  // ── Vær / Weather ─────────────────────────────────────────────────────────
  { id: 'sw-var-001', word: 'torden',       emoji: '⛈️', category: 'vær',   difficulty: 6  },
  { id: 'sw-var-002', word: 'lyn',          emoji: '⚡', category: 'vær',    difficulty: 5  },
  { id: 'sw-var-003', word: 'orkan',        emoji: '🌀', category: 'vær',    difficulty: 6  },
  { id: 'sw-var-004', word: 'hagl',         emoji: '🌨️', category: 'vær',   difficulty: 5  },
  { id: 'sw-var-005', word: 'tåke',         emoji: '🌫️', category: 'vær',   difficulty: 5  },
  { id: 'sw-var-006', word: 'varme',        emoji: '🌡️', category: 'vær',   difficulty: 6  },
  { id: 'sw-var-007', word: 'kulde',        emoji: '🥶', category: 'vær',    difficulty: 6  },
  { id: 'sw-var-008', word: 'snøstorm',     emoji: '❄️', category: 'vær',   difficulty: 8  },
  { id: 'sw-var-009', word: 'årstider',     emoji: '🌸', category: 'vær',    difficulty: 8  },

  // ── Romvesen / Space ──────────────────────────────────────────────────────
  { id: 'sw-rom-001', word: 'planet',       emoji: '🪐', category: 'rom',    difficulty: 6  },
  { id: 'sw-rom-002', word: 'stjerne',      emoji: '⭐', category: 'rom',    difficulty: 7  },
  { id: 'sw-rom-003', word: 'komet',        emoji: '☄️', category: 'rom',   difficulty: 6  },
  { id: 'sw-rom-004', word: 'galakse',      emoji: '🌌', category: 'rom',    difficulty: 7  },
  { id: 'sw-rom-005', word: 'asteroide',    emoji: '🪨', category: 'rom',    difficulty: 9  },
  { id: 'sw-rom-006', word: 'svart hull',   emoji: '🕳️', category: 'rom',   difficulty: 9  },
  { id: 'sw-rom-007', word: 'rakett',       emoji: '🚀', category: 'rom',    difficulty: 7  },
  { id: 'sw-rom-008', word: 'teleskop',     emoji: '🔭', category: 'rom',    difficulty: 8  },
  { id: 'sw-rom-009', word: 'måne',         emoji: '🌕', category: 'rom',    difficulty: 5  },
  { id: 'sw-rom-010', word: 'solflekkene',  emoji: '☀️', category: 'rom',   difficulty: 10 },
]

export function getSpellWordsForDifficulty(difficulty: number): Word[] {
  return spellWords.filter(w => Math.abs(w.difficulty - difficulty) <= 1)
}
