import type { Word } from './types'

export const words: Word[] = [
  // ── dyr (animals) ──────────────────────────────────────────────
  { id: 'dyr-001', word: 'hund',        emoji: '🐶', category: 'dyr', difficulty: 1  },
  { id: 'dyr-002', word: 'katt',        emoji: '🐱', category: 'dyr', difficulty: 1  },
  { id: 'dyr-003', word: 'ku',          emoji: '🐄', category: 'dyr', difficulty: 1  },
  { id: 'dyr-004', word: 'gris',        emoji: '🐷', category: 'dyr', difficulty: 1  },
  { id: 'dyr-005', word: 'fugl',        emoji: '🐦', category: 'dyr', difficulty: 2  },
  { id: 'dyr-006', word: 'fisk',        emoji: '🐟', category: 'dyr', difficulty: 2  },
  { id: 'dyr-007', word: 'hest',        emoji: '🐴', category: 'dyr', difficulty: 2  },
  { id: 'dyr-008', word: 'bjørn',       emoji: '🐻', category: 'dyr', difficulty: 3  },
  { id: 'dyr-009', word: 'elefant',     emoji: '🐘', category: 'dyr', difficulty: 3  },
  { id: 'dyr-010', word: 'løve',        emoji: '🦁', category: 'dyr', difficulty: 4  },
  { id: 'dyr-011', word: 'tiger',       emoji: '🐯', category: 'dyr', difficulty: 4  },
  { id: 'dyr-012', word: 'pingvin',     emoji: '🐧', category: 'dyr', difficulty: 4  },
  { id: 'dyr-013', word: 'krokodille',  emoji: '🐊', category: 'dyr', difficulty: 5  },
  { id: 'dyr-014', word: 'neshorn',     emoji: '🦏', category: 'dyr', difficulty: 5  },
  { id: 'dyr-015', word: 'flodhest',    emoji: '🦛', category: 'dyr', difficulty: 6  },
  { id: 'dyr-016', word: 'sjiraff',     emoji: '🦒', category: 'dyr', difficulty: 6  },
  { id: 'dyr-017', word: 'sjimpanse',   emoji: '🐒', category: 'dyr', difficulty: 7  },
  { id: 'dyr-018', word: 'dodo',  emoji: '🦤', category: 'dyr', difficulty: 8  },
  { id: 'dyr-019', word: 'salamander',   emoji: '🦎', category: 'dyr', difficulty: 9  },
  { id: 'dyr-020', word: 'tyrannosaurus rex',  emoji: '🦖', category: 'dyr', difficulty: 10 },

  // ── mat (food) ──────────────────────────────────────────────────
  { id: 'mat-001', word: 'eple',        emoji: '🍎', category: 'mat', difficulty: 1  },
  { id: 'mat-002', word: 'brød',        emoji: '🍞', category: 'mat', difficulty: 1  },
  { id: 'mat-003', word: 'melk',        emoji: '🥛', category: 'mat', difficulty: 1  },
  { id: 'mat-004', word: 'egg',         emoji: '🥚', category: 'mat', difficulty: 1  },
  { id: 'mat-005', word: 'ost',         emoji: '🧀', category: 'mat', difficulty: 2  },
  { id: 'mat-006', word: 'fisk',        emoji: '🐟', category: 'mat', difficulty: 2  },
  { id: 'mat-007', word: 'banan',       emoji: '🍌', category: 'mat', difficulty: 2  },
  { id: 'mat-008', word: 'jordbær',     emoji: '🍓', category: 'mat', difficulty: 3  },
  { id: 'mat-009', word: 'sjokolade',   emoji: '🍫', category: 'mat', difficulty: 3  },
  { id: 'mat-010', word: 'spagetti',    emoji: '🍝', category: 'mat', difficulty: 4  },
  { id: 'mat-011', word: 'appelsin',    emoji: '🍊', category: 'mat', difficulty: 4  },
  { id: 'mat-012', word: 'brokkoli',    emoji: '🥦', category: 'mat', difficulty: 5  },
  { id: 'mat-013', word: 'ananas',      emoji: '🍍', category: 'mat', difficulty: 5  },
  { id: 'mat-014', word: 'vannmelon',   emoji: '🍉', category: 'mat', difficulty: 5  },
  { id: 'mat-015', word: 'blåbær',      emoji: '🫐', category: 'mat', difficulty: 6  },
  { id: 'mat-016', word: 'blomkål',     emoji: '🥦', category: 'mat', difficulty: 6  },
  { id: 'mat-017', word: 'mandarin',    emoji: '🍊', category: 'mat', difficulty: 7  },
  { id: 'mat-018', word: 'kokosnøtt',   emoji: '🥥', category: 'mat', difficulty: 8  },
  { id: 'mat-019', word: 'persille',    emoji: '🌿', category: 'mat', difficulty: 9  },
  { id: 'mat-020', word: 'pære',    emoji: '🍐', category: 'mat', difficulty: 10 },

  // ── klær (clothing) ─────────────────────────────────────────────
  { id: 'kla-001', word: 'caps',         emoji: '🧢', category: 'klær', difficulty: 1  },
  { id: 'kla-002', word: 'sko',         emoji: '👟', category: 'klær', difficulty: 1  },
  { id: 'kla-003', word: 'bukse',       emoji: '👖', category: 'klær', difficulty: 1  },
  { id: 'kla-004', word: 't-skjorte',     emoji: '👕', category: 'klær', difficulty: 2  },
  { id: 'kla-005', word: 'kjole',       emoji: '👗', category: 'klær', difficulty: 2  },
  { id: 'kla-006', word: 'sokker',        emoji: '🧦', category: 'klær', difficulty: 2  },
  { id: 'kla-007', word: 'jakke',       emoji: '🧥', category: 'klær', difficulty: 3  },
  { id: 'kla-008', word: 'strikke',      emoji: '🧶', category: 'klær', difficulty: 3  },
  { id: 'kla-009', word: 'regnjakke',   emoji: '🧥', category: 'klær', difficulty: 4  },
  { id: 'kla-010', word: 'votter',      emoji: '🧤', category: 'klær', difficulty: 4  },
  { id: 'kla-011', word: 'skjerf',       emoji: '🧣', category: 'klær', difficulty: 4  },
  { id: 'kla-012', word: 'vindjakke',   emoji: '🧥', category: 'klær', difficulty: 5  },
  { id: 'kla-013', word: 'shorts',      emoji: '🩳', category: 'klær', difficulty: 5  },
  { id: 'kla-014', word: 'badedrakt',   emoji: '👙', category: 'klær', difficulty: 6  },
  { id: 'kla-015', word: 'ullgenser',   emoji: '🧶', category: 'klær', difficulty: 7  },
  { id: 'kla-016', word: 'støvler',     emoji: '👢', category: 'klær', difficulty: 6  },
  { id: 'kla-017', word: 'regnbukse',   emoji: '👖', category: 'klær', difficulty: 7  }, 
  { id: 'kla-018', word: 'kimono', emoji: '👘', category: 'klær', difficulty: 8  },
  { id: 'kla-019', word: 'regnfrakk',   emoji: '🧥', category: 'klær', difficulty: 9  },
  { id: 'kla-020', word: 'dongeribukse',  emoji: '👖', category: 'klær', difficulty: 10 },

  // ── kropp (body) ─────────────────────────────────────────────────
  { id: 'kro-001', word: 'hånd',        emoji: '✋', category: 'kropp', difficulty: 1  },
  { id: 'kro-002', word: 'fot',         emoji: '🦶', category: 'kropp', difficulty: 1  },
  { id: 'kro-003', word: 'øye',         emoji: '👁️', category: 'kropp', difficulty: 1  },
  { id: 'kro-004', word: 'nese',        emoji: '👃', category: 'kropp', difficulty: 1  },
  { id: 'kro-005', word: 'munn',        emoji: '👄', category: 'kropp', difficulty: 2  },
  { id: 'kro-006', word: 'øre',         emoji: '👂', category: 'kropp', difficulty: 2  },
  { id: 'kro-007', word: 'arm',         emoji: '💪', category: 'kropp', difficulty: 2  },
  { id: 'kro-008', word: 'ben',         emoji: '🦵', category: 'kropp', difficulty: 2  },
  { id: 'kro-009', word: 'vinke',     emoji: '🤚', category: 'kropp', difficulty: 3  },
  { id: 'kro-010', word: 'kne',         emoji: '🦵', category: 'kropp', difficulty: 3  },
  { id: 'kro-011', word: 'albue',       emoji: '💪', category: 'kropp', difficulty: 4  },
  { id: 'kro-012', word: 'ankel',       emoji: '🦶', category: 'kropp', difficulty: 4  },
  { id: 'kro-013', word: 'hot dog',       emoji: '🌭', category: 'kropp', difficulty: 4  },
  { id: 'kro-014', word: 'pølse i brød',   emoji: '🌭', category: 'kropp', difficulty: 5  },
  { id: 'kro-015', word: 'håndflate',    emoji: '✋', category: 'kropp', difficulty: 6  },
  { id: 'kro-016', word: 'kjøttstykke',   emoji: '🥩', category: 'kropp', difficulty: 7  },
  { id: 'kro-017', word: 'kyllinglår',     emoji: '🍗', category: 'kropp', difficulty: 7  },
  { id: 'kro-018', word: 'hundebein',     emoji: '🦴', category: 'kropp', difficulty: 8  },
  { id: 'kro-019', word: 'lunger',  emoji: '🫁', category: 'kropp', difficulty: 9  },
    { id: 'kro-020', word: 'hjerte', emoji: '🫀', category: 'kropp', difficulty: 10 },
  
        // -- Smiley / Emotions ─────────────────────────────────────────────────────────────
    { id: 'sw-smi-001', word: 'glad', emoji: '😀', category: 'smiley', difficulty: 5 },
    { id: 'sw-smi-002', word: 'trist', emoji: '😢', category: 'smiley', difficulty: 5 },
    { id: 'sw-smi-003', word: 'sint', emoji: '😠', category: 'smiley', difficulty: 5 },
    { id: 'sw-smi-004', word: 'overrasket', emoji: '😲', category: 'smiley', difficulty: 6 },
    { id: 'sw-smi-005', word: 'skuffet', emoji: '😞', category: 'smiley', difficulty: 6 },
    { id: 'sw-smi-006', word: 'forvirret', emoji: '😕', category: 'smiley', difficulty: 6 },
    { id: 'sw-smi-007', word: 'stolt', emoji: '😌', category: 'smiley', difficulty: 7 },
    { id: 'sw-smi-008', word: 'redd', emoji: '😨', category: 'smiley', difficulty: 7 },
    { id: 'sw-smi-009', word: 'lei seg', emoji: '😔', category: 'smiley', difficulty: 7 },
    { id: 'sw-smi-010', word: 'fornøyd', emoji: '😊', category: 'smiley', difficulty: 5 },
    { id: 'sw-smi-011', word: 'latter', emoji: '🤣', category: 'smiley', difficulty: 6 },
    { id: 'sw-smi-012', word: 'kjempeglad', emoji: '🤩', category: 'smiley', difficulty: 7 },
    { id: 'sw-smi-013', word: 'smile', emoji: '😊', category: 'smiley', difficulty: 5 },
    { id: 'sw-smi-014', word: 'OK', emoji: '👌', category: 'smiley', difficulty: 5 },
    { id: 'sw-smi-015', word: 'pengesekk', emoji: '💰', category: 'smiley', difficulty: 5 },
    { id: 'sw-smi-016', word: 'solbriller', emoji: '😎', category: 'smiley', difficulty: 5 },
    { id: 'sw-smi-017', word: 'glovarm', emoji: '🥵', category: 'smiley', difficulty: 6 },
    { id: 'sw-smi-018', word: 'termometer', emoji: '🌡️', category: 'smiley', difficulty: 7 },
    { id: 'sw-smi-019', word: 'stetoskop', emoji: '🩺', category: 'smiley', difficulty: 7 },
    { id: 'sw-smi-020', word: 'kvalm', emoji: '🤢', category: 'smiley', difficulty: 7 },
    { id: 'sw-smi-021', word: 'feiring', emoji: '🥳', category: 'smiley', difficulty: 7 },
    { id: 'sw-smi-022', word: 'forvirret', emoji: '🥴', category: 'smiley', difficulty: 7 },
    { id: 'sw-smi-023', word: 'uvel', emoji: '🤒', category: 'smiley', difficulty: 7 },
    { id: 'sw-smi-024', word: 'crazy', emoji: '🤪', category: 'smiley', difficulty: 7 },
    { id: 'sw-smi-025', word: 'sint', emoji: '🤬', category: 'smiley', difficulty: 7 },
    { id: 'sw-smi-026', word: 'hodeskalle', emoji: '💀', category: 'smiley', difficulty: 7 },
    { id: 'sw-smi-027', word: 'spøkelse', emoji: '👻', category: 'smiley', difficulty: 7 },
    { id: 'sw-smi-028', word: 'robot', emoji: '🤖', category: 'smiley', difficulty: 7 },

  // ── transport ───────────────────────────────────────────────────
  { id: 'tra-001', word: 'bil',         emoji: '🚗', category: 'transport', difficulty: 1  },
  { id: 'tra-002', word: 'buss',        emoji: '🚌', category: 'transport', difficulty: 1  },
  { id: 'tra-003', word: 'tog',         emoji: '🚂', category: 'transport', difficulty: 1  },
  { id: 'tra-004', word: 'seilbåt',         emoji: '⛵', category: 'transport', difficulty: 1  },
  { id: 'tra-005', word: 'fly',         emoji: '✈️', category: 'transport', difficulty: 2  },
  { id: 'tra-006', word: 'sykkel',      emoji: '🚲', category: 'transport', difficulty: 2  },
  { id: 'tra-007', word: 'traktor',     emoji: '🚜', category: 'transport', difficulty: 3  },
  { id: 'tra-008', word: 'lastebil',    emoji: '🚚', category: 'transport', difficulty: 3  },
  { id: 'tra-009', word: 'brannbil',    emoji: '🚒', category: 'transport', difficulty: 4  },
  { id: 'tra-010', word: 'ambulanse',   emoji: '🚑', category: 'transport', difficulty: 5  },
  { id: 'tra-011', word: 'helikopter',  emoji: '🚁', category: 'transport', difficulty: 5  },
  { id: 'tra-012', word: 'motorsykkel', emoji: '🏍️', category: 'transport', difficulty: 5  },
  { id: 'tra-013', word: 'skateboard',  emoji: '🛹', category: 'transport', difficulty: 5  },
  { id: 'tra-014', word: 'sparkesykkel',emoji: '🛴', category: 'transport', difficulty: 6  },
  { id: 'tra-015', word: 'ferge',        emoji: '🚢', category: 'transport', difficulty: 6  },
  { id: 'tra-016', word: 'ballong', emoji: '🎈', category: 'transport', difficulty: 7  },
  { id: 'tra-017', word: 'propellfly',      emoji: '🛩️', category: 'transport', difficulty: 7  },
  { id: 'tra-018', word: 'cruiseskip',     emoji: '🛳️', category: 'transport', difficulty: 8  },
  { id: 'tra-019', word: 'uidentifisert flygende objekt', emoji: '🛸', category: 'transport', difficulty: 9  },
  { id: 'tra-020', word: 'undergrunnsbane', emoji: '🚇', category: 'transport', difficulty: 10 },

  // ── natur (nature) ───────────────────────────────────────────────
  { id: 'nat-001', word: 'sol',         emoji: '☀️', category: 'natur', difficulty: 1  },
  { id: 'nat-002', word: 'sky',         emoji: '☁️', category: 'natur', difficulty: 1  },
  { id: 'nat-003', word: 'regn',        emoji: '🌧️', category: 'natur', difficulty: 1  },
  { id: 'nat-004', word: 'snøkrystall', emoji: '❄️', category: 'natur', difficulty: 1 },
  { id: 'nat-005', word: 'snø',         emoji: '❄️', category: 'natur', difficulty: 1  },
  { id: 'nat-006', word: 'tre',         emoji: '🌳', category: 'natur', difficulty: 2  },
  { id: 'nat-007', word: 'blomst',      emoji: '🌸', category: 'natur', difficulty: 2  },
  { id: 'nat-008', word: 'skog',        emoji: '🌲', category: 'natur', difficulty: 2  },
  { id: 'nat-009', word: 'fjell',       emoji: '⛰️', category: 'natur', difficulty: 3  },
  { id: 'nat-010', word: 'pizzastykke',      emoji: '🍕', category: 'natur', difficulty: 3  },
  { id: 'nat-011', word: 'innsjø',         emoji: '🏞️', category: 'natur', difficulty: 3  },
  { id: 'nat-012', word: 'strand',      emoji: '🏖️', category: 'natur', difficulty: 4  },
  { id: 'nat-013', word: 'ørkenlandskap',       emoji: '🏜️', category: 'natur', difficulty: 4  },
  { id: 'nat-014', word: 'fjelltopp',       emoji: '🏔️', category: 'natur', difficulty: 5  },
  { id: 'nat-015', word: 'eikenøtt',    emoji: '🌰', category: 'natur', difficulty: 5  },
  { id: 'nat-016', word: 'snøvær',      emoji: '🌨️', category: 'natur', difficulty: 6  },
  { id: 'nat-017', word: 'vulkan',      emoji: '🌋', category: 'natur', difficulty: 6  },
  { id: 'nat-018', word: 'tordenvær',   emoji: '⛈️', category: 'natur', difficulty: 7  },
  { id: 'nat-019', word: 'jordklode',  emoji: '🌍', category: 'natur', difficulty: 8  },
  { id: 'nat-020', word: 'monsun',      emoji: '🌊', category: 'natur', difficulty: 9  },
  { id: 'nat-021', word: 'melkeveien',    emoji: '🌌', category: 'natur', difficulty: 10 },

  // ── hus (home) ───────────────────────────────────────────────────
  { id: 'hus-001', word: 'dør',         emoji: '🚪', category: 'hus', difficulty: 1  },
  { id: 'hus-002', word: 'vindu',       emoji: '🪟', category: 'hus', difficulty: 1  },
  { id: 'hus-003', word: 'stol',        emoji: '🪑', category: 'hus', difficulty: 1  },
  { id: 'hus-004', word: 'ping pong',        emoji: '🏓', category: 'hus', difficulty: 1  },
  { id: 'hus-005', word: 'seng',        emoji: '🛏️', category: 'hus', difficulty: 2  },
  { id: 'hus-006', word: 'lyspære',       emoji: '💡', category: 'hus', difficulty: 2  },
  { id: 'hus-007', word: 'stekepanne',     emoji: '🍳', category: 'hus', difficulty: 3  },
  { id: 'hus-008', word: 'badekar',         emoji: '🛁', category: 'hus', difficulty: 2  },
  { id: 'hus-009', word: 'sofa',        emoji: '🛋️', category: 'hus', difficulty: 3  },
  { id: 'hus-010', word: 'trapp',       emoji: '🪜', category: 'hus', difficulty: 3  },
  { id: 'hus-011', word: 'isbit',   emoji: '🧊', category: 'hus', difficulty: 4  },
  { id: 'hus-012', word: 'bålflamme',      emoji: '🔥', category: 'hus', difficulty: 4  },
  { id: 'hus-013', word: 'handlekurv', emoji: '🧺', category: 'hus', difficulty: 5  },
  { id: 'hus-014', word: 'feiekost',   emoji: '🧹', category: 'hus', difficulty: 5  },
  { id: 'hus-015', word: 'såpebobler',emoji: '🫧', category: 'hus', difficulty: 6  },
  { id: 'hus-016', word: 'søppelkasse', emoji: '🗑️', category: 'hus', difficulty: 7  },
  { id: 'hus-017', word: 'papirkurv', emoji: '🗑️', category: 'hus', difficulty: 7  },
  { id: 'hus-018', word: 'kvadratisk vindu',emoji: '🪟', category: 'hus', difficulty: 7  },
  { id: 'hus-019', word: 'enebolig',    emoji: '🏠', category: 'hus', difficulty: 8  },
  { id: 'hus-020', word: 'peisflamme',        emoji: '🔥', category: 'hus', difficulty: 4  },
  { id: 'hus-021', word: 'vedkubbe',      emoji: '🪵', category: 'hus', difficulty: 9  },

  // ── skole (school) ───────────────────────────────────────────────
  { id: 'sko-001', word: 'bøker',         emoji: '📚', category: 'skole', difficulty: 1  },
  { id: 'sko-002', word: 'penn',        emoji: '✏️', category: 'skole', difficulty: 1  },
  { id: 'sko-003', word: 'linjal',      emoji: '📏', category: 'skole', difficulty: 2  },
  { id: 'sko-004', word: 'svamp',    emoji: '🧽', category: 'skole', difficulty: 2  },
  { id: 'sko-005', word: 'tavle',       emoji: '🧑‍🏫', category: 'skole', difficulty: 2  },
  { id: 'sko-006', word: 'skolebuss',  emoji: '🚌', category: 'skole', difficulty: 4  },
  { id: 'sko-007', word: 'skolesekk',   emoji: '🎒', category: 'skole', difficulty: 3  },
  { id: 'sko-008', word: 'blyant',      emoji: '✏️', category: 'skole', difficulty: 3  },
  { id: 'sko-009', word: 'vinkel',      emoji: '📐', category: 'skole', difficulty: 5  },
  { id: 'sko-010', word: 'globus',      emoji: '🌍', category: 'skole', difficulty: 4  },
  { id: 'sko-011', word: 'atlas',       emoji: '🗺️', category: 'skole', difficulty: 5  },
  { id: 'sko-012', word: 'ordbok',      emoji: '📖', category: 'skole', difficulty: 5  },
  { id: 'sko-013', word: 'lærebok',     emoji: '📕', category: 'skole', difficulty: 6  },
  { id: 'sko-014', word: 'notatblokk',  emoji: '📓', category: 'skole', difficulty: 6  },
  { id: 'sko-015', word: 'mappe',  emoji: '🗂️', category: 'skole', difficulty: 7  },
  { id: 'sko-016', word: 'binders',emoji: '📎', category: 'skole', difficulty: 7  },
  { id: 'sko-017', word: 'tegnestift',  emoji: '📌', category: 'skole', difficulty: 8  },
  { id: 'sko-018', word: 'graf', emoji: '📊', category: 'skole', difficulty: 8  },
  { id: 'sko-019', word: 'datamaskin', emoji: '🖥️', category: 'skole', difficulty: 9 },
  { id: 'sko-020', word: 'mikrofon',    emoji: '🎤', category: 'skole', difficulty: 9  },

  // ── sport ────────────────────────────────────────────────────────
  { id: 'spo-001', word: 'ball',        emoji: '⚽', category: 'sport', difficulty: 1  },
  { id: 'spo-002', word: 'ski',         emoji: '⛷️', category: 'sport', difficulty: 1  },
  { id: 'spo-003', word: 'fotball',     emoji: '⚽', category: 'sport', difficulty: 2  },
  { id: 'spo-004', word: 'svømming',    emoji: '🏊', category: 'sport', difficulty: 3  },
  { id: 'spo-005', word: 'sykling',     emoji: '🚴', category: 'sport', difficulty: 3  },
  { id: 'spo-006', word: 'løping',      emoji: '🏃', category: 'sport', difficulty: 3  },
  { id: 'spo-007', word: 'basketball',  emoji: '🏀', category: 'sport', difficulty: 4  },
  { id: 'spo-008', word: 'tennis',      emoji: '🎾', category: 'sport', difficulty: 4  },
  { id: 'spo-009', word: 'badminton',   emoji: '🏸', category: 'sport', difficulty: 5  },
  { id: 'spo-010', word: 'volleyball',  emoji: '🏐', category: 'sport', difficulty: 5  },
  { id: 'spo-011', word: 'håndball',    emoji: '🤾', category: 'sport', difficulty: 5  },
  { id: 'spo-012', word: 'medalje',   emoji: '🏅', category: 'sport', difficulty: 6  },
  { id: 'spo-013', word: 'kampsport',   emoji: '🥋', category: 'sport', difficulty: 6  },
  { id: 'spo-014', word: 'kompass', emoji: '🧭', category: 'sport', difficulty: 7  },
  { id: 'spo-015', word: 'roing',       emoji: '🚣', category: 'sport', difficulty: 6  },
  { id: 'spo-016', word: 'klatring',    emoji: '🧗', category: 'sport', difficulty: 7  },
  { id: 'spo-017', word: 'skateboard',  emoji: '🛹', category: 'sport', difficulty: 7  },
  { id: 'spo-018', word: 'snowboard',   emoji: '🏂', category: 'sport', difficulty: 7  },
  { id: 'spo-019', word: 'svømming',    emoji: '🏊', category: 'sport', difficulty: 9  },
  { id: 'spo-020', word: 'jogging',  emoji: '🏃', category: 'sport', difficulty: 8  },

  // ── musikk (music) ───────────────────────────────────────────────
  { id: 'mus-001', word: 'note',        emoji: '🎵', category: 'musikk', difficulty: 1  },
  { id: 'mus-002', word: 'trommer',     emoji: '🥁', category: 'musikk', difficulty: 2  },
  { id: 'mus-003', word: 'gitar',       emoji: '🎸', category: 'musikk', difficulty: 2  },
  { id: 'mus-004', word: 'piano',       emoji: '🎹', category: 'musikk', difficulty: 2  },
  { id: 'mus-005', word: 'tre noter',      emoji: '🎶', category: 'musikk', difficulty: 3  },
  { id: 'mus-006', word: 'fiolin',      emoji: '🎻', category: 'musikk', difficulty: 3  },
  { id: 'mus-007', word: 'trompet',     emoji: '🎺', category: 'musikk', difficulty: 4  },
  { id: 'mus-008', word: 'tuba',        emoji: '🎷', category: 'musikk', difficulty: 4  },
  { id: 'mus-009', word: 'saksofon',    emoji: '🎷', category: 'musikk', difficulty: 5  },
  { id: 'mus-010', word: 'trekkspill',  emoji: '🪗', category: 'musikk', difficulty: 5  },
  { id: 'mus-011', word: 'noter',   emoji: '🎶', category: 'musikk', difficulty: 6  },
  { id: 'mus-012', word: 'cello',       emoji: '🎻', category: 'musikk', difficulty: 6  },
  { id: 'mus-013', word: 'kontrabass',  emoji: '🎻', category: 'musikk', difficulty: 7  },
  { id: 'mus-014', word: 'cd',         emoji: '💿', category: 'musikk', difficulty: 7  },
  { id: 'mus-015', word: 'øretelefoner',      emoji: '🎧', category: 'musikk', difficulty: 8  },
  { id: 'mus-016', word: 'mute',       emoji: '🔇', category: 'musikk', difficulty: 7  },
  { id: 'mus-017', word: 'megafon',     emoji: '📢', category: 'musikk', difficulty: 8  },
  { id: 'mus-018', word: 'posthorn',     emoji: '📯', category: 'musikk', difficulty: 9  },
  { id: 'mus-019', word: 'flygel',     emoji: '🎹', category: 'musikk', difficulty: 9  },
  { id: 'mus-020', word: 'slagverk',    emoji: '🥁', category: 'musikk', difficulty: 10 },

  // ── farger (colors) ──────────────────────────────────────────────
  { id: 'far-001', word: 'rød',         emoji: '🔴', category: 'farger', difficulty: 1  },
  { id: 'far-002', word: 'blå',         emoji: '🔵', category: 'farger', difficulty: 1  },
  { id: 'far-003', word: 'gul',         emoji: '🟡', category: 'farger', difficulty: 1  },
  { id: 'far-004', word: 'grønn',       emoji: '🟢', category: 'farger', difficulty: 1  },
  { id: 'far-005', word: 'hvit',        emoji: '⬜', category: 'farger', difficulty: 2  },
  { id: 'far-006', word: 'svart',       emoji: '⬛', category: 'farger', difficulty: 2  },
  { id: 'far-007', word: 'rosa',        emoji: '🩷', category: 'farger', difficulty: 2  },
  { id: 'far-008', word: 'oransje',     emoji: '🟠', category: 'farger', difficulty: 3  },
  { id: 'far-009', word: 'lilla',       emoji: '🟣', category: 'farger', difficulty: 3  },
  { id: 'far-010', word: 'brun',        emoji: '🟤', category: 'farger', difficulty: 3  },
  { id: 'far-011', word: 'grå',         emoji: '🩶', category: 'farger', difficulty: 3  },
  { id: 'far-012', word: 'turkis',      emoji: '🔵', category: 'farger', difficulty: 4  },
  { id: 'far-013', word: 'høst',        emoji: '🍂', category: 'farger', difficulty: 5  },
  { id: 'far-014', word: 'trekløver',       emoji: '☘️', category: 'farger', difficulty: 5  },
  { id: 'far-015', word: 'korall',      emoji: '🪸', category: 'farger', difficulty: 6  },
  { id: 'far-016', word: 'støvelett',      emoji: '👢', category: 'farger', difficulty: 6  },
  { id: 'far-017', word: 'kunstløp',     emoji: '⛸️', category: 'farger', difficulty: 7  },
  { id: 'far-018', word: 'skøyter',   emoji: '⛸️', category: 'farger', difficulty: 8  },
  { id: 'far-019', word: 'snømann',     emoji: '⛄', category: 'farger', difficulty: 9  },
  { id: 'far-020', word: 'flosshatt',     emoji: '🎩', category: 'farger', difficulty: 10 },

  // ── tall (numbers) ────────────────────────────────────────────────
  { id: 'tal-001', word: 'én',          emoji: '1️⃣', category: 'tall', difficulty: 1  },
  { id: 'tal-002', word: 'to',          emoji: '2️⃣', category: 'tall', difficulty: 1  },
  { id: 'tal-003', word: 'tre',         emoji: '3️⃣', category: 'tall', difficulty: 1  },
  { id: 'tal-004', word: 'fire',        emoji: '4️⃣', category: 'tall', difficulty: 1  },
  { id: 'tal-005', word: 'fem',         emoji: '5️⃣', category: 'tall', difficulty: 2  },
  { id: 'tal-006', word: 'seks',        emoji: '6️⃣', category: 'tall', difficulty: 2  },
  { id: 'tal-007', word: 'syv',         emoji: '7️⃣', category: 'tall', difficulty: 2  },
  { id: 'tal-008', word: 'åtte',        emoji: '8️⃣', category: 'tall', difficulty: 2  },
  { id: 'tal-009', word: 'ni',          emoji: '9️⃣', category: 'tall', difficulty: 3  },
  { id: 'tal-010', word: 'ti',          emoji: '🔟', category: 'tall', difficulty: 3  },
  { id: 'tal-011', word: 'hashtag',        emoji: '#️⃣', category: 'tall', difficulty: 3  },
  { id: 'tal-012', word: 'stjerne',      emoji: '*️⃣', category: 'tall', difficulty: 4  },
  { id: 'tal-013', word: 'null',       emoji: '0️⃣', category: 'tall', difficulty: 4  },
  { id: 'tal-014', word: 'bokstaver',       emoji: '🔠', category: 'tall', difficulty: 5  },
  { id: 'tal-015', word: 'hundre',      emoji: '💯', category: 'tall', difficulty: 5  },
  { id: 'tal-016', word: 'nødsignal',       emoji: '🆘', category: 'tall', difficulty: 6  },
  { id: 'tal-017', word: 'flamme',     emoji: '🔥', category: 'tall', difficulty: 7  },
  { id: 'tal-018', word: 'halvparten',  emoji: '½', category: 'tall', difficulty: 6  },
  { id: 'tal-019', word: 'tredjedel',   emoji: '⅓', category: 'tall', difficulty: 8  },
  { id: 'tal-020', word: 'fjerdedel',   emoji: '¼', category: 'tall', difficulty: 9  },
]

export function getWordsByCategory(category: string): Word[] {
  return words.filter(w => w.category === category)
}

export function getWordsForDifficulty(difficulty: number): Word[] {
  // Return words within ±1 difficulty level
  return words.filter(w => Math.abs(w.difficulty - difficulty) <= 1)
}
